### ISSUE TITLE
Bot does not start on debian - fails at opening chrome

### ISSUE THREAD

**Issue by justmemaarten** [vasani-arpit/WBOT#10]
**Describe the bug**

**To Reproduce**
1. Go to 'cd (map)'
2. Run command  './wbot-linux'
3. See error
4. ██╗    ██╗██████╗  ██████╗ ████████╗
██║    ██║██╔══██╗██╔═══██╗╚══██╔══╝
██║ █╗ ██║██████╔╝██║   ██║   ██║   
██║███╗██║██╔══██╗██║   ██║   ██║   
╚███╔███╔╝██████╔╝╚██████╔╝   ██║   
 ╚══╝╚══╝ ╚═════╝  ╚═════╝    ╚═╝   
                                    

reading file from/home/debian/WBOT-linux-0.5
reading file from/home/debian/WBOT-linux-0.5
✔ Downloading chrome ... done!
⣾ Launching ChromeLooks like you got an error.Error: Failed to launch chrome!
/home/debian/WBOT-linux-0.5/linux-638880/chrome-linux/chrome: error while loadin

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/trou

(node:5595) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 's
    at Main (/snapshot/WBOT/src/index.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This 
(node:5595) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
⣾

**Expected behavior**
I want a qr code in the terminal of my server so i can start the bot correctly.

**Screenshots**
http://prntscr.com/nlv62x

**App information (please complete the following information):**
 - Version [9.0]
 - OS: [Debian]

**Comment by vasani-arpit** [comment]
I don't have Debian environment. but I think you need to have sudo access in order to launch Chrome. 
check if you can run sample from https://github.com/GoogleChrome/puppeteer 
This may be just a config issues or your distro is missing an library/package which chrome needs in order to start.

**Comment by vasani-arpit** [comment]
Closing as this is machine specific issue. Feel free to reopen if you find something new.
