### ISSUE TITLE
Whatsappweb QRCODE div class update on 02 Feb 2020

### ISSUE THREAD

**Issue by adjie46** [vasani-arpit/WBOT#101]
I will test WBOT on version last beta.
I see whatsapp web update html element

I success to update code for read new qrcode
change code in index.js from 

await page.waitForSelector("canvas[aria-label='Scan me!']");
        var imageData = await page.evaluate(`document.querySelector("canvas[aria-label='Scan me!']").parentElement.getAttribute("data-ref")`);

to

await page.waitForSelector("._2RT36");
        var imageData = await page.evaluate(`document.querySelector("._2RT36").getAttribute("data-ref")`);

**Comment by MAZETAM** [comment]
@adjie46 
There is not something wrong with current code that used selector "canvas[.....".
Why you said it as bug?

**Comment by vasani-arpit** [comment]
@adjie46 
Yes. The code is updated but binaries has not been added as release that's why there is this confusion. I will release a version soon. Once I am done reviewing all PRs.

**Comment by vasani-arpit** [comment]
Resolved in latest release.
