### ISSUE TITLE
I got error running nodemon

### ISSUE THREAD

**Issue by indragunawan82** [vasani-arpit/WBOT#102]
![Capture](https://user-images.githubusercontent.com/9045625/73604082-bcfc2c80-45bd-11ea-8f1c-3481fae4b6a8.JPG)

**Comment by vasani-arpit** [comment]
You need to install following dependencies

```
sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
```

**Comment by indragunawan82** [comment]
problem still occur

**Comment by vasani-arpit** [comment]
@gnadelwartz, Will you help @indragunawan82? This looks like your expertise.

**Comment by gnadelwartz** [comment]
do you run on a Linux server without running x11 or display not set?

if yes you can use xvfb virtual x11 server to run WBOT.
Ubuntu?

http://manpages.ubuntu.com/manpages/trusty/man1/xvfb-run.1.html

**Comment by indragunawan82** [comment]
![image](https://user-images.githubusercontent.com/9045625/73755583-d0172400-4798-11ea-9ac2-4995d3142e5d.png)




![image](https://user-images.githubusercontent.com/9045625/73755637-e8873e80-4798-11ea-9c06-e13af78b6974.png)



not working

**Comment by indragunawan82** [comment]
does this WBOT working in ubuntu? or i should change to other OS (exclude windows) ?

**Comment by gnadelwartz** [comment]
may be I missed something, but was is the command nodemon? usually you start WBOT wizh the command wbot?

nevertheless to have a running X11 you must use

```
xvgfb-run wbot

or (maybe) in your case

xvfb-run noderun
```

if this dies not work for you you may try on windows or mac

**Comment by gnadelwartz** [comment]
ah, I see what nodemon us for.
does wbot run if you start it manually?

**Comment by indragunawan82** [comment]
![image](https://user-images.githubusercontent.com/9045625/73764897-4cfcca80-47a6-11ea-9441-e141e1065f1a.png)

**Comment by gnadelwartz** [comment]
you must be in the base dir, not src dir, try

```
cd /var/www/html/WBOT-0.11
node src/index.js
```

**Comment by indragunawan82** [comment]
![image](https://user-images.githubusercontent.com/9045625/73765707-7ff38e00-47a7-11ea-83ec-7c9afeef97cf.png)

**Comment by gnadelwartz** [comment]
xvfb-run node src/index.js

if this does not go further, I'm done ...

**Comment by indragunawan82** [comment]
The main problem is ENOENT sir
why this ENOENT happened?

**Comment by indragunawan82** [comment]
![image](https://user-images.githubusercontent.com/9045625/73766002-f7c1b880-47a7-11ea-8876-e497885a6642.png)



does anyone able to run WBOT in ubuntu 18 ?

**Comment by gnadelwartz** [comment]
enoent say: file or dir does not exist, dies the chrome binary is in the path shown?

**Comment by indragunawan82** [comment]
![image](https://user-images.githubusercontent.com/9045625/73766505-b1b92480-47a8-11ea-88a1-172fb667a43a.png)




nothing in there sir

**Comment by gnadelwartz** [comment]
rm the complete Linux-xxx path and try again ...

only to be shure, the user you are using is owner of WBOT dir has full acess right to it?

**Comment by gnadelwartz** [comment]
as last ressort change hhe following line 

https://github.com/vasani-arpit/WBOT/blob/1f172d5af63a3765dc22cbb742b60ba78113e1f5/src/index.js#L73

to point to native chrome installation on Ubuntu...


`which chromium-browser` should show the installation path

**Comment by ryahpalma** [comment]
I also tried to use the nodemon but was unsuccessful.

**Comment by vasani-arpit** [comment]
Try localtunnel @ryahpalma @indragunawan82

**Comment by indragunawan82** [comment]
![image](https://user-images.githubusercontent.com/9045625/74108164-00e8c600-4baa-11ea-9040-5b916323defd.png)



previouse error are fix, now i got new error

**Comment by indragunawan82** [comment]
![image](https://user-images.githubusercontent.com/9045625/74109540-e1a46580-4bb6-11ea-9b80-cfa908071e85.png)


why i always go to exception?
