### ISSUE TITLE
Centos 7 : WhatsApp works with Google Chrome 49+

### ISSUE THREAD

**Issue by catur515** [vasani-arpit/WBOT#104]
Sorry my bad english... this text using google translate from my language to english.. sory.

OS Centos 7 :
==========
**WABOT works perfectly for the first time login in headless mode: true**,
However, if it is closed with ctrl + c ctrl Z or kill node js;
If run again then :
check login page.evaluate("localStorage['last-wid']"); // it's okey but then 
**error :**
WhatsApp works with Google Chrome 49+ :

Ia have try by handle with SIGINT SIGTERM; but its not working.
The message  WhatsApp works with Google Chrome 49+, always show.

so I have to delete chromium-data, than scanqrcode again every time the computer restarts or after press ctrl+c.

**Comment by vasani-arpit** [comment]
Please pull the latest code and use it. ```localStorage['last-wid']``` is no longer being used. I used to have this problem I think latest one will not have that problem.

**Comment by catur515** [comment]
> Please pull the latest code and use it. `localStorage['last-wid']` is no longer being used. I used to have this problem I think latest one will not have that problem.

Sori, 
Do you mean checklogin no longer using await page.evaluate ("localStorage ['wid-wid']");
But Sorry I did not find the file.

**Comment by vasani-arpit** [comment]
I have access to ubuntu machine. I will try in it.

**Comment by catur515** [comment]
I'm still, 
get error like this.... 

![error](https://user-images.githubusercontent.com/22145610/73715997-59523a80-4748-11ea-88ec-6c9d9d9d3208.png)

**Comment by catur515** [comment]
after a few days, almost a week I've found a solution headless on centos:
use the following useragent:

page.setUserAgent ('Mozilla / 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit / 537.36 (KHTML, like Gecko) Version / 4.0 Chrome / 55.0.2883.91 Mobile Safari / 537.36')
