### ISSUE TITLE
Someone can give me example to use webhook?

### ISSUE THREAD

**Issue by yaelahsas** [vasani-arpit/WBOT#105]
im new to use wbot, i try to learn about bot. i think i can make some bot can response question like simsimi but i dont know to implement in wbot. can you give me example to make simsimi or implement webhook

**Comment by impozzible** [comment]
What's your programming language

**Comment by yaelahsas** [comment]
Php,
In case how i can config wbot to connect with server with response json? Bcs in documentation, we have to add rule in wbot, but i not understand where the rule create

**Comment by impozzible** [comment]
Just provide link to your php script in the bot.json and in your script receive post request and do processing then return response

**Comment by yaelahsas** [comment]
How i can get response from web in wbot? Sorry im still learn about this

**Comment by impozzible** [comment]
<?php
header('Access-Control-Allow-Origin: *');
header("Access-Control-Allow-Credentials: true");
header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
header('Access-Control-Max-Age: 1000');
header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token , Authorization');
// file_put_contents("wh.txt",$postdata);
$data = file_get_contents("php://input");
$data = json_decode($data,true);
$text = $data['text'];
$type = $data['type'];
$user = $data['user'];

$response = array("text" => "Kilon sele my nigga", "type" => "message");
$response = json_encode($response);
echo "[$response]";

**Comment by impozzible** [comment]
`
<?php
header('Access-Control-Allow-Origin: *');
header("Access-Control-Allow-Credentials: true");
header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
header('Access-Control-Max-Age: 1000');
header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token , Authorization');
// file_put_contents("wh.txt",$postdata);
$data = file_get_contents("php://input");
$data = json_decode($data,true);
$text = $data['text'];
$type = $data['type'];
$user = $data['user'];

$response = array("text" => "Kilon sele my nigga", "type" => "message");
$response = json_encode($response);
echo "[$response]";

`

**Comment by yaelahsas** [comment]
Sorry, in my case i cant get response from web an then send to whatsapp, not how to make response in server

**Comment by impozzible** [comment]
You mean initiate conversation from php to node server?

**Comment by yaelahsas** [comment]
Yesss, right

**Comment by impozzible** [comment]
You will need to contact @vasani-arpit for that

**Comment by yaelahsas** [comment]
You use webhook?

**Comment by impozzible** [comment]
The one I use, is what i explained above

**Comment by yaelahsas** [comment]
Oke i see, thanks for your response :)

**Comment by yaelahsas** [comment]
@impozzible  if you get response from web server , what next to send it to contact whatsapp?

**Comment by impozzible** [comment]
https://drive.google.com/file/d/1XREpk7RroD8UwWk-Kdkh-dj72_L8HS68/view?usp=sharing
Check the video here

**Comment by yaelahsas** [comment]
Thanks i will tryy

**Comment by yaelahsas** [comment]
@impozzible  btw how to add webapi in wbot ? Bcs in bot.json webapi is undefined

**Comment by impozzible** [comment]
You can add it manually, but I don't think it's required so you may leave it out

**Comment by yaelahsas** [comment]
Btw, can i change type request note "message" but "pesan"? In where i can change? Maybe in inject.js?

**Comment by impozzible** [comment]
maybe I guess so

**Comment by yaelahsas** [comment]
Okey thankss :)

**Comment by yaelahsas** [comment]
@impozzible  are u adding some code in config of WBOT? bcs i try its not working, in example i just set to your webhook

**Comment by impozzible** [comment]
No just add link in your bot.json

**Comment by yaelahsas** [comment]
can i see your webapi function? bcs i add your link in my bot.json not working. or i have to create some code like 

`const express = require('express')
const app = express()
const port = 3001
//allowing requests from outside of the domain 
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*"); // update to match the domain you will make the request from
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type,Accept");
  next();
});

app.post('/api/incoming-webhook', (req, res) => res.send(
    [{
      "text": "Look, Reply from Webhook!",
      "type": "message"
    }]
))
app.get('/', (req, res) => res.send('Hello World!'))

app.listen(port, () => console.log(`Example app listening on port ${port}!`))`

**Comment by impozzible** [comment]
No, I still don't understand your problem

**Comment by yaelahsas** [comment]
@impozzible  if i add your link to bot.json why still not connected to your link, but in your video you just add link and its working fine.

**Comment by beecoder77** [comment]
@impozzible @vasani-arpit 
well, same as me,,, using node js too, when I change the webhook (here I use locahost), when I chat to the bot, the server does not receive any requests from wbot

**Comment by beecoder77** [comment]
well, same as me, I have changed the webhook (here I use locahost) and the webapi setting is true, when I chat to the bot, the server / webhook does not receive any requests from wbot

@impozzible @vasani-arpit @yaelahsas

**Comment by impozzible** [comment]
Are you sure you configured your server correctly, I am currently using the api for this now, and it's working perectly. https://cutt.ly/covid19bot

**Comment by yaelahsas** [comment]
@impozzible  do you change inject.js?

**Comment by yaelahsas** [comment]
Bcs, i try to code simple php like your video buts the no respond if i run wbot

**Comment by impozzible** [comment]
No i did not change inject.js, send your php code, let me check

**Comment by yaelahsas** [comment]
@impozzible here response web
![image](https://user-images.githubusercontent.com/34953546/77359214-d039a600-6d7d-11ea-9aa4-6ad1e60e248b.png)

**Comment by impozzible** [comment]
Screenshot php code and send let me check

**Comment by yaelahsas** [comment]
@impozzible  thiss
![image](https://user-images.githubusercontent.com/34953546/77359500-3de5d200-6d7e-11ea-924e-450f23e3eae0.png)

**Comment by impozzible** [comment]
I think, you change type to pesan in the library so you need to change type in your php script to pessan also

**Comment by yaelahsas** [comment]
if i test in post man, result is not change 
![image](https://user-images.githubusercontent.com/34953546/77360475-feb88080-6d7f-11ea-8856-cccbc737d460.png)

**Comment by impozzible** [comment]
change type in wa.php to pesan
$response = array('text'=>$reply,'type'=>"pesan");

**Comment by yaelahsas** [comment]
not change the response, if i test in postman. i think php script not get data from postman, and then reply is ididnt understand.

**Comment by impozzible** [comment]
I don't understand you

**Comment by yaelahsas** [comment]
Give me tutorial about @impozzible

**Comment by intec-id** [comment]
great example @impozzible , this what I need.

**Comment by yaelahsas** [comment]
@intec-id  can u give example to change type message in library?

**Comment by intec-id** [comment]
> `<?php
> header('Access-Control-Allow-Origin: *');
> header("Access-Control-Allow-Credentials: true");
> header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
> header('Access-Control-Max-Age: 1000');
> header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token , Authorization');
> // file_put_contents("wh.txt",$postdata);
> $data = file_get_contents("php://input");
> $data = json_decode($data,true);
> $text = $data['text'];
> $type = $data['type'];
> $user = $data['user'];
> 
> $response = array("text" => "Kilon sele my nigga", "type" => "message");
> $response = json_encode($response);
> echo "[$response]";`

this sample work perfect, you just need set-up webhook in bot.json @yaelahsas

**Comment by yaelahsas** [comment]
@intec-id  but if i run bot response from server no work

**Comment by yaelahsas** [comment]
@impozzible  @intec-id  why response default from server not printed in console ?

**Comment by impozzible** [comment]
Hello, do you have teamviewer

**Comment by yaelahsas** [comment]
@impozzible  yes i have, can u teach me with teamview?

**Comment by impozzible** [comment]
yes,

**Comment by yaelahsas** [comment]
@impozzible  okey, lets go meeting, or remote control?

**Comment by impozzible** [comment]
remote control

**Comment by impozzible** [comment]
Kindly have your Php script open and then the WBOT server up also

**Comment by yaelahsas** [comment]
Okeyy
ID : 1345092788
Pass: 8tz67a

**Comment by impozzible** [comment]
<img width="1337" alt="Screenshot 2020-03-25 at 2 57 16 PM" src="https://user-images.githubusercontent.com/30698707/77544320-25bea180-6ea9-11ea-85bc-ac37ec6c3880.png">
