### ISSUE TITLE
INCOMING WEBHOOK

### ISSUE THREAD

**Issue by tradename** [vasani-arpit/WBOT#108]
How can i implement an incoming webhook to post message to whatsapp and it not being neccessarily a reply to a message. For example, to send a notification to a WhatsApp user without having him/her to send something first,..... can i just initiate a conversation from my webhook.

**Comment by egorky** [comment]
Hi! I would like to know that as well. Can someone help us? :) 👍

**Comment by egorky** [comment]
Hi @vasani-arpit , I understand that Whatsapp have policies but what I want is to simply send messages to my phone regarding alarms from my networking equipment. Is that use case possible?

**Comment by oOHiyoriOo** [comment]
would love to have this as well since i want make some notifications for me using this.
