### ISSUE TITLE
Startup bug

### ISSUE THREAD

**Issue by justmemaarten** [vasani-arpit/WBOT#11]
after some adjustments in bot.json and i try to restart wbot i get the following error

reading file from/Users/maarten
reading file from/Users/maarten
(node:41443) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/maarten/bot.json'
(node:41443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:41443) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Looks like you got an error.Error: ENOENT: no such file or directory, open '/Users/maarten/bot.json'
(node:41443) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'screenshot' of undefined
    at Main (/snapshot/WBOT/src/index.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:41443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Mac-mini-van-Maarten:~ maarten$

**Comment by justmemaarten** [comment]
Here a screenshot http://prntscr.com/nlvk5p Running on macos mojave 10.12.4

**Comment by vasani-arpit** [comment]
WBOT needs bot.json to be present at same directory with it.

**Your steps should be as per following:** 

1. Download release version 0.5 zip from Github
2. Extract/unzip into a new directory 
3. CD to that directory 
4. start the WBOT with sudo 

Closing this one. Feel free to reopen again if you face the same issue again.
