### ISSUE TITLE
contactBlock returns setBlock is not a function

### ISSUE THREAD

**Issue by joweste** [vasani-arpit/WBOT#110]
**Describe the bug**
window.WAPI.contactBlock and window.WAPI.uncontactBlock returns
contact.setBlock is not a function at Object.window.WAPI.contactBlock

**To Reproduce**
1.Steps to reproduce the behavior:
2.Load the wapi.js into chrome dev console
3.execute in chrome dev console: window.WAPI.uncontactBlock("5521.....@c.us")
4.The error will show

**Expected behavior**
The contact should be blocked

**App information (please complete the following information):**
 - Version : Latest
 - OS: windows 10

**Comment by vasani-arpit** [comment]
@andersondeoliveiramachado Will you take a look at this?
