### ISSUE TITLE
deleteMessage is not working

### ISSUE THREAD

**Issue by joweste** [vasani-arpit/WBOT#111]
**Describe the bug**
Hi there,
I am trying to delete a message.
I am using
WAPI.deleteMessage ("5521...@c.us","false_5521971319071@c.us_A74600FAFF70DB0C7286A0FD329567B1", true);

The function returns true.
Next, I use WAPI.getAllMessagesInChat ("5521...@c.us",.....
And the message just deleted continues appearing in the return list of messages
If i set the revoke param true or false make no difference

**To Reproduce**
1. Load the wapi.js into chrome dev console
2. execute in chrome dev console: window.WAPI.uncontactBlock("5521.....@c.us")
3. No error occur
4. execute the command in console WAPI.getAllMessagesInChat(......) 
5.The messsage just deleted appears again

**Expected behavior**

**App information (please complete the following information):**
 - Version latest
 - OS: windows 10

**Comment by vasani-arpit** [comment]
@andersondeoliveiramachado Will you take a look at this?

**Comment by andersondeoliveiramachado** [comment]
> @andersondeoliveiramachado Will you take a look at this?
this is a lib question https://github.com/mukulhase/WebWhatsapp-Wrapper

You are not really deleting the message.
![image](https://user-images.githubusercontent.com/1152426/74878528-46de2080-5346-11ea-87b0-d852f31abc49.png)

**Comment by andersondeoliveiramachado** [comment]
Delete with revoke = False
WAPI.deleteMessage = function (chatId, messageArray, revoke = false, done)

![image](https://user-images.githubusercontent.com/1152426/74879804-adfcd480-5348-11ea-9201-613788118478.png)

**Comment by joweste** [comment]
Thank you very much. I will try.
Now, I did  a small fix to sendContact.
The problem for now is:
The function only send the contact to someone if that contact has  a chat.
So, I did the next change and now, I can send the contact disregarding if he has a chat or not:

```
/**
 * Send contact card to a specific chat using the chat ids
 *
 * @param {string} to '000000000000@c.us'
 * @param {string|array} contact '111111111111@c.us' | ['222222222222@c.us', '333333333333@c.us, ... 'nnnnnnnnnnnn@c.us']
 */
window.WAPI.sendContact = function (to, contact) {
    if (!Array.isArray(contact)) {
        contact = [contact];
    }
    contact = contact.map((c) => {
        let found = window.Store.Contact.get(c);
        if (found) return found;
    });

    if (contact.length > 1) {
        window.WAPI.getChat(to).sendContactList(contact);
    } else if (contact.length === 1) {
        window.WAPI.getChat(to).sendContact(contact[0]);
    }
    return true;
};

```

Sometimes I do some changes. Where is the better place to post them?

**Comment by andersondeoliveiramachado** [comment]
> Thank you very much. I will try.
> Now, I did a small fix to sendContact.
> The problem for now is:
> The function only send the contact to someone if that contact has a chat.
> So, I did the next change and now, I can send the contact disregarding if he has a chat or not:
> 
> ```
> /**
>  * Send contact card to a specific chat using the chat ids
>  *
>  * @param {string} to '000000000000@c.us'
>  * @param {string|array} contact '111111111111@c.us' | ['222222222222@c.us', '333333333333@c.us, ... 'nnnnnnnnnnnn@c.us']
>  */
> window.WAPI.sendContact = function (to, contact) {
>     if (!Array.isArray(contact)) {
>         contact = [contact];
>     }
>     contact = contact.map((c) => {
>         let found = window.Store.Contact.get(c);
>         if (found) return found;
>     });
> 
>     if (contact.length > 1) {
>         window.WAPI.getChat(to).sendContactList(contact);
>     } else if (contact.length === 1) {
>         window.WAPI.getChat(to).sendContact(contact[0]);
>     }
>     return true;
> };
> ```
> 
> Sometimes I do some changes. Where is the better place to post them?

In https://github.com/mukulhase/WebWhatsapp-Wrapper
