### ISSUE TITLE
sendImage Function is not working

### ISSUE THREAD

**Issue by didom900** [vasani-arpit/WBOT#112]
**Describe the bug**
When I use the sendImage function on wapi.js file, doesn't works.

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]
 - additional info which might be useful to reproduce the issue

**Additional context**

**Comment by vasani-arpit** [comment]
It is working. For it's use and parameters. Please have a look at 

https://github.com/vasani-arpit/WBOT/blob/master/src/inject.js#L66

**Comment by catur515** [comment]
same here also 3 hours ago, can't send pictures
with error:
**TypeError: Store.MediaCollection is not a constructor**

**Comment by joweste** [comment]
I haver the same problem. The sendImage  stops to working

**Comment by catur515** [comment]
**I found this... and Yes.. its working again...** 

https://github.com/mukulhase/WebWhatsapp-Wrapper/commit/69c587fd38f727ad0e13f54eb8de003485bad4c6

**Comment by vasani-arpit** [comment]
Issue fixed https://github.com/vasani-arpit/WBOT/pull/106
