### ISSUE TITLE
Make app resizable

### ISSUE THREAD

**Issue by victoryudi** [vasani-arpit/WBOT#113]
Is there anyway to make the Wpp app resizable? Chromium does resize but the wpp web itself seems to be fixed. @vasani-arpit

**Comment by vasani-arpit** [comment]
change this on [index.js](https://github.com/vasani-arpit/WBOT/blob/master/src/index.js#L72)

```js
const browser = await puppeteer.launch({
            executablePath: revisionInfo.executablePath,
            headless: appconfig.appconfig.headless,
            userDataDir: path.join(process.cwd(), "ChromeSession"),
            devtools: false,
            defaultViewport:null //<------------------------------ add this option
            args: [...constants.DEFAULT_CHROMIUM_ARGS, ...pptrArgv], ...extraArguments
});
```

You can read full documentation on it [here](https://pptr.dev/#?product=Puppeteer&version=v2.1.1&show=api-puppeteerlaunchoptions)
