### ISSUE TITLE
Can't run Mac OS 10.15.2

### ISSUE THREAD

**Issue by andrrrrey** [vasani-arpit/WBOT#115]
(node:16816) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/andrey/bot.json'
(node:16816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Looks like you got an error. Error: ENOENT: no such file or directory, open '/Users/andrey/bot.json'
Can't create shreenshot, X11 not running?. TypeError: Cannot read property 'screenshot' of undefined
{ [Error: ENOENT: no such file or directory, open '/Users/andrey/bot.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/andrey/bot.json' }
Don't worry errors are good. They help us improve. A screenshot has already been saved as error.png in current directory. Please mail it on vasani.arpit@gmail.com along with the steps to reproduce it.

(node:16816) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/andrey/bot.json'
(node:16816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

Plz help!

**Comment by vasani-arpit** [comment]
@pavanmehta91

**Comment by pavanmehta91** [comment]
the binary takes the path of bot.json as /Users/{name} 
i.e user's home whereas in all the cases.
Whereas it should read from the folder the binary is run from.

**Comment by pavanmehta91** [comment]
@andrrrrey you can but bot.json at `'/Users/andrey/bot.json' for now. Copy the json file available in the zip and paste it on the said path. 
Will fix this
