### ISSUE TITLE
Doesn't start after closing the bot

### ISSUE THREAD

**Issue by Suleman-Elahi** [vasani-arpit/WBOT#12]
**Describe the bug**
After closing the bot via Ctrl+C or Directly, the bot won't start next time. The Window opens and then disappears.

![image](https://user-images.githubusercontent.com/24384996/57358290-b6f23000-7192-11e9-963b-c5dc7d906247.png)

I am using it on Windows 10, 1809.

**Comment by vasani-arpit** [comment]
Please make sure bot.json is valid. This would help https://jsonlint.com

**Comment by Suleman-Elahi** [comment]
Yes I did. I didn't even touch the "bot.json" file.

**Comment by vasani-arpit** [comment]
Can you reproduce it? I can't 
Check this gif
![BiDc99Y310](https://user-images.githubusercontent.com/6497827/57444649-3dc80b00-726e-11e9-860d-cf544da5ceb8.gif)

bare with me sometimes windows goes outside the recording region

**Comment by vasani-arpit** [comment]
Assuming this is resolved. Feel free to reopen if issue persists.
