### ISSUE TITLE
Error Running in chrome, webhok for send images

### ISSUE THREAD

**Issue by yaelahsas** [vasani-arpit/WBOT#120]
![image](https://user-images.githubusercontent.com/34953546/77661281-014bed80-6fad-11ea-9cc8-ab78eac546d6.png)

i use php server
@vasani-arpit

**Comment by HelioSilva** [comment]
apparently it could be a CORS error

**Comment by andersondeoliveiramachado** [comment]
disable CORS policy in (Puppeteer) with : 

--disable-web-security

**Comment by yaelahsas** [comment]
I was set like your code @andersondeoliveiramachado  but still rejected,

**Comment by yaelahsas** [comment]
Any solution @HelioSilva

**Comment by HelioSilva** [comment]
@yaelahsas your webhook is with node? If it is with express add:

const express  = require('express');
**const cors = require('cors');** <----------------
const mongoose = require('mongoose');
const requireDir = require("require-dir");


const app = express();
**app.use(cors());** < ------------------
app.use(express.json());

**Comment by vasani-arpit** [comment]
Looks like so many people are having trouble with webhook one.  I am sorry I have been planning on making a video but couldn't find right hardware. Looks like I need to use whatever does the job.

**Comment by HelioSilva** [comment]
The concept of webhook is perfect, with me now everything is working
