### ISSUE TITLE
WAPI is not defined

### ISSUE THREAD

**Issue by victorhdchagas** [vasani-arpit/WBOT#121]
Something happened after whatsapp Update.
when i swap between chats, i receive a error: 
WAPI is not defined.

this is my first issue report, i hope we can get some solution for this.

![Capturar](https://user-images.githubusercontent.com/8129003/77702785-08b4cc00-6f98-11ea-8103-e07c6402acf6.PNG)

**Comment by tpjezy** [comment]
VM46 __puppeteer_evaluation_script__:8 Uncaught ReferenceError: WAPI is not defined
    at MutationObserver.<anonymous> (VM21 __puppeteer_evaluation_script__:8)

Also getting this same error

**Comment by eddysby2000** [comment]
please help?
![wa-err](https://user-images.githubusercontent.com/7475873/77733849-20dd2780-703a-11ea-81e1-238cd84381be.png)

**Comment by eddysby2000** [comment]
if (typeof webpackJsonp === 'function') {
    webpackJsonp([], {'parasite': (x, y, z) => getStore(z)}, ['parasite']);
} else {
    webpackJsonp.push([
        ['parasite'],
        {
            parasite: function (o, e, t) {
                getStore(t);
            }
        },
        [['parasite']]
    ]);
}

**Comment by robertsLando** [comment]
@eddysby2000 How to fix that?

**Comment by marcosxp** [comment]
Is this problem in the ZIP file?
Mine stopped working too

**Comment by HelioSilva** [comment]
Thanks **@robertsLando**, bug solved.
![Captura de Tela (98)](https://user-images.githubusercontent.com/12967010/77772288-a656dc80-7026-11ea-8a56-0b049ffe7b46.png)

**Comment by victorhdchagas** [comment]
> Thanks **@robertsLando**, bug solved.
> ![Captura de Tela (98)](https://user-images.githubusercontent.com/12967010/77772288-a656dc80-7026-11ea-8a56-0b049ffe7b46.png)

what u did?

**Comment by robertsLando** [comment]
@victorhdchagas He has used my pull request https://github.com/vasani-arpit/WBOT/pull/122

**Comment by victorhdchagas** [comment]
> @victorhdchagas He has used my pull request #122

i saw it, probably your answer is about the other image in this issue. 
sorry i'm confused

**Comment by victorhdchagas** [comment]
I don't understand why WAPI is not defined, but i see the
![Capturar](https://user-images.githubusercontent.com/8129003/77774291-9391d700-7029-11ea-9dd5-643163dd365a.PNG)
 script in webwhatsapp inspector.

**Comment by robertsLando** [comment]
It isn't defined because it throws an error while initing. The error thrown is fixed in the pr

**Comment by HelioSilva** [comment]
@victorhdchagas , he made a change to the wiapi.js file, then you change your file and the problem solves

**Comment by marcosxp** [comment]
Someone could compile and leave it without the bug to download,

I don't know how to compile with NODE, just download and configure the webhook.

Now I'm at hand, if anyone can do this kindness I appreciate

**Comment by HelioSilva** [comment]
@marcosxp  
[WBOT Update temp.zip](https://github.com/vasani-arpit/WBOT/files/4395525/WBOT.Update.temp.zip)

**Comment by cbeltrangomez84** [comment]
Sorry, how this thing "webpackJsonp" and "parasite" works? it import a library? from where? Thanks a lot for the fix

**Comment by vasani-arpit** [comment]
Fix added to WBOT in latest release.
