### ISSUE TITLE
Help sending image with caption from webhook 

### ISSUE THREAD

**Issue by AI-man001** [vasani-arpit/WBOT#123]
**I've been trying to send image with caption from web-hook. The image is coming from a URL. When I run it I get only the caption no image. What am I missing here. below is my PHP code.** 

    header('Access-Control-Allow-Origin: *');
    header("Access-Control-Allow-Credentials: true");
    header('Access-Control-Allow-Methods: GET, PUT, POST, DELETE, OPTIONS');
    header('Access-Control-Max-Age: 1000');
    header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token , Authorization');

    $url = 'https://image.freepik.com/free-photo/image-human-brain_99433-298.jpg';
    $image = file_get_contents($url);

    $caption ="Testing Image with caption";
    $media= 'data:image/jpg;base64,'.base64_encode($image);
    $reply =array('text' => $caption,'type' => 'message','files' =>[array('name' => 'Image','file' => 'data:image/jpg;base64,'.$media)]);
    $response = json_encode([$reply]);
    echo $response;

**Comment by andersondeoliveiramachado** [comment]
![image](https://user-images.githubusercontent.com/1152426/77803359-b2a95c80-705b-11ea-9ae6-a4b473835ace.png)
The mime is repeated, that could be it.

**Comment by HelioSilva** [comment]
I cannot send images as a response.

`
data = fs.readFileSync('C://Users//Hélio Silva//Desktop//chatBot3//WBOT//src//foto.jpg');
let media = data.toString('base64') ;
`

    res.send(  
    [{
        "text": "Look, quick replies!",
        "type": "message",
        "files":[{
            "name":"foto.jpg",
            "file":"data:image/jpg;base64,"+media
        }]


![gitphoto](https://user-images.githubusercontent.com/12967010/77805950-12a30180-7062-11ea-8076-1ceb2e45ebd7.png)

**Comment by AI-man001** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1152426/77803359-b2a95c80-705b-11ea-9ae6-a4b473835ace.png)
> The mime is repeated, that could be it.

indeed that was the problem solved now thanks
