### ISSUE TITLE
No sending images via webhook - Fixed

### ISSUE THREAD

**Issue by HelioSilva** [vasani-arpit/WBOT#124]
**No sending images via webhook**
File: inject.js.
When obtaining the return from the webhook, the "response" is expected, I believe that recently this file has become an array. As a result, "response [0]" is used to send text messages, but "response.files" is used for images, which results in an "undefined" variable.

**To Reproduce**
1. Send Image via WebHook

**Comment by vasani-arpit** [comment]
Merged. Thanks for reporting !!
