### ISSUE TITLE
Sending audio message.

### ISSUE THREAD

**Issue by AI-man001** [vasani-arpit/WBOT#126]
I was able to send image but when I send audio? The audio is send but its not playable

**'data:audio/mp3;base64,'.base64_encode("http://localhost/bot/audio_test.mp3");**

What am I missing here

**Comment by HelioSilva** [comment]
I just did this test and it's working here. Are you using the latest release?

**Comment by AI-man001** [comment]
Ok it worked I was using old version.

**Comment by AI-man001** [comment]
How about sending message to a number without having the number sending message to me first

**Comment by HelioSilva** [comment]
@AI-man001  I believe that it is not possible!
