### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by justmemaarten** [vasani-arpit/WBOT#13]
If i restart the program if it work it keeps downloading chrome again and again and ask me again and again or a new qr code

**Comment by vasani-arpit** [comment]
Just confirmed. This is happening on windows as well. Seems like chrome arguments from last commit has something to do with it.

**Comment by vasani-arpit** [comment]
Resolved in version 0.5-beta. Tested in Windows.

**Comment by samik9** [comment]
Hello Arpit im getting this error when I rebooted my Mac, this is with latest version https://d.pr/i/TWpdoK

**Comment by vasani-arpit** [comment]
Wbot is unable to download Google Chrome. Google faced outrage on certain region recently. May be this is one of them. Please try again after. Feel free to report if issue persists.

**Comment by mrlck** [comment]
Hi! have the same problem https://prnt.sc/nyibs9 how to fix it?

**Comment by vasani-arpit** [comment]
Use the development branch. I added the fix today in it. Will merge to master tonight or tomorrow.

**Comment by zoutepopcorn** [comment]
I've got an error also

```
⡿ Downloading chrome
(node:8606) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'branch_base_position' of ud
    at getRevNumber.fetch.then.then.json (/snapshot/WBOT/src/detectRev.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either b)
⣻ Downloading chrome
```

On Arch linux. I just added index.js

```
I've got an error also

```
⡿ Downloading chrome
(node:8606) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'branch_base_position' of ud
    at getRevNumber.fetch.then.then.json (/snapshot/WBOT/src/detectRev.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either b)
⣻ Downloading chrome
```

On Arch linux. I just put in this, on index.js

```javascript
        // var revNumber = await rev.getRevNumber();
        const revNumber = 666595;
``

**Comment by vasani-arpit** [comment]
Yes. I'll be removing that code in next release as it is not being used.
