### ISSUE TITLE
Doesn't work on RPI 3B, Raspbian Buster

### ISSUE THREAD

**Issue by Tsjippy** [vasani-arpit/WBOT#131]
I have moved the wbot-linux file to my RPI, gave it a chmod 777, and executed, but nothing happens.
I double click it, it asks me if I want to execute it or Execute it in terminal. If I click on either of them, nothing happens.

**Comment by vasani-arpit** [comment]
I haven't checked it in other than Ubuntu. If binary is not working for you then I suggest you to install node and npm. Clone the source and run ```npm run app```.

**Comment by xynz** [comment]
Keep in mind RPI is ARM.
like me tested for 4 day with 4 OS in my RP4.
i forget the bin file not support arm.

you can run with git clone.
