### ISSUE TITLE
encrypted message with file or image

### ISSUE THREAD

**Issue by hasanbasri1993** [vasani-arpit/WBOT#134]
**Describe the bug**
encrypted message with file or image

**To Reproduce**
I set my bot.json
and set webook to https://hasanbasri.free.beeceptor.com/wa
 "appconfig": {
        "headless": true,
        "isGroupReply":false,
        "webhook":"https://hasanbasri.free.beeceptor.com/wa"
    },

**Expected behavior**
i got body post like this

{"text":"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCABUAGQDASIAAhEBAxEB/8QAHQAAAQQDAQEAAAAAAAAAAAAAAAUGBwgDBAkCAf/EADkQAAIBAwMCAwUGBQMFAAAAAAECAwQFEQASIQYxBxNBCBQiUWFxgZGhsfAVIzJSwdHh8UJTYnKC/8QAGgEAAgMBAQAAAAAAAAAAAAAAAwQBAgUABv/EACsRAAEEAQMDAwIHAAAAAAAAAAEAAgMRBBIhMRNBUSIycYGRBTNSocHw8f/aAAwDAQACEQMRAD8AXelnqv4zUtLFJHHBURrCS6nzlMY+MDPHJZfQ5U+h1IyRxVCqHRZNq9zzj14Oo4sdxDdS1FuKVCinpKaqLeWNhDySLhW9WHlnI9Ayn11JFIwDALg89iBn8P8AT66DwUAElbiWxTh42Kbu6847fd9NKFPS1CHBG/jgg5/zrzA4ADZyQP8Ap/f7xpRpZAuGYYZv7RjP7/xqL8qwWajaRSoJ7nt9NK61crQqhJ4yDz3OtGNleNGdAxA7f762lQFvhK7e3P01WypoFZHnwoUnkY4x3/fOsctRheNuR+WvDB2xuUcH0ORrBIyqAMkbeBg8/brrXLzNPIygqPXvnOT9o1BXXPtF+HvSniBTdN13Uz+dSOKWsjgxJHG0pBG9dwbchVDuUPtVpAVGQdTVXTBYndGI4PbjnXMq9We3Wq5dddc9TzUNfUPbXioYbnAtTurKqZwk2JDtXygIkAKkDzASRswQPlp7WebXNjL734C6G+/01fTR1tHURyQzoskTqch1YZDD9dNTqay01wuFDc6+SctbGkmgQEbN7RlN2CO4UsAc5wx+em77PlfU1vgd0dVVEzSTPa4vic5JwSPTsAOMegH005b/AFksVFVTRgySJC5jX5naSP8ATR2HU0EoQurC8PXSxuQu5gSTxyB+WjSTVODL8W4YHHGjRNNqunyq1UXtiQkRzJ0MPKIKkm7ZPOD/ANr6DvqZvBH2kYfFvqSv6di6Wa1GioTVNMK8TgkSKnl4CLgndnOT2+o1QiyWhZ6L3SrZqaSImNkEeGRlypBUr3GDnUh+H/ilbPZ+6gN9ieruaXGlFIyyQrH5ZDxuxwCdw/l7M5BAIbHAXWrkYkbYi9o3+UFkjnSaSukz3Smoqd6mpYwwxqu98EhR2yccgD1PYDk4AOmTfvaW8Jel7hTW2s6sgrpauFZY0tmKx2DPtjCxw7nfcVfkKQAuWIyuebHi97Unid4p186peqyx2iSJ6c2231kqRSxMm11lxt8wMCwIKgYbBGokhuVwp51qYa6dJUxtdZCGGMev3D8BrLEY7p4NPddibX7UXhDdblTWi1dQz1r1DtD5lPSSMFm82KNYimPMZmM2QVQqBG+5lO0NLcFxQoCrghhxg98/rxrhNT3+5wyRTrXz76dmkjy54du7D0DfX7++p78DPbL8QPCi6xwX641XVPT8ixQzUVZWTPNTRoGC+7M5Kx4Lj4cYKoB8PBEOi29Kml1m97JTO48D4frzrSqasK25yT6d/wAdMvo/xDsfXXTNt6r6arxU22604qYJcYODwVYejAgqV9CCNKE1esuD5owDxkgfv10qT5XJRq6vPw5IUqVyflqlPi17L3VV/wDEC53q1WykudJcqxqrNXUskUYZI0AVEkRtyhTySM7QM4Pw23qKxdhjDk+gOf39dJk9bHtx2BYnIHr89Vr1Ag8KDY3Cb/Q/TkXQPQ9n6OjqDJ/CqdYA7NkHHfkKM9z3A1luNQs0ckc8aPG+Q4cZDD1BB7/86zVlfHGGO4kdsE9zpt3G5lcl2BOcBSePn92isFCkOqFBeaq4ZlJWZf8A6bB/zo02pruVlbavfk4HfRoui91U0qXQW6poohS+6i3ismf3JCrsJATkJGdwMhG5QfUHggHgRp19Nd47y9qvEdTBNRkq8M8bRsG/u2tk4K7Tyfn6Y1fix3mjhpYbt0zS2iKlqaeGSmjNrg8nyyCyyJiMOCysg5YgBFwASSaee03DcH8Sprrcmd57jF57Mzu4JLsSAXYkAZGFGFUbQBgDTZzzOOnVK0eP03alEmjS7D0pUzU4mEwDHspX1+Wk6rtNbRybJI8g9mHbSzZ43nSDunnY0rRqLVp6M8caUBZKohcFdzLu2nOcaw1VtqaNBJMoAJ2jnVhKwmgVDoJGiy3ZWJ9jLxybw/6rqukOpL+KXp2708kiCplVIKerQBhIXcgRho1dTj+pvLBHAIvVB1nR3a1QX2yyPdaCqI8qooFFRG652lgyZVgD3wT2PfXI+x1lJb71QV9fSiqpaepilngZQwljVgWQg8HIyMH56mW2+MPVV96htF9uV8rLlVVU0tRNBTD3l6b+aWkTyZFBAMfIKybceoIYLV8bSbKAV0ba6LLHkOMep9QdJ81eCC7vggfPnUG+CnifV9VLeqatr6qc01aZKdKqGOGSnpHAWKL+XlXw8UwLE7uASAGUCSZrmwJZXPOAvpzpUijuuq1vVtwADMWDHBAPqPw+mmV1Z1RR2iklrLjWQ00EeMyzOqICSFAJPbJIA+pHrrNdL9BCWV5OTyVB/fy1UP2pb5LP1jbhFUTER0IZkJby498j8qM4DNsO7gE7FyTgAEYNRUBoPKd159p2CG61VLb6CFYqaZ4d1QzlpCrEbxjGARjjvnOjVZqitqJZNxkYcAfDx+mjTQIrdo/dXMDAfcVfDp5qKjsdHa6KuWYW5P4d8mYwHyW/pHGGRgfs1FftGdLT3/paG/QUqCqssrVGGqFDmlI/mEIDxyI2BPOFIHPBlGCKKha42231wkC11TJPlseXLLIZyjYBPaYED5FSfTDd6/oI710febTUSxRJPSSnftEaowyys2O+CMkk4x6azg7Q7ZXCrw0S7gizR7QMfA+cADtr29reQNC8YYk7s5Hp+/z0nX2zUNFXMtJ09OZHbCSxzttGTyeDn7tbNEJkt8olnm3ouVLnJGccZ/51lvaANTT/AH7lengcXelwWrX08EORNOgKcFmOMcZ9efXSBdGjqqdoqeoWbYu4kHsdbZopmO82n3yV+C0z5P28/h6a2IbO8NHK1RBFCWG3y0Xn6ZOnIy2GnE2fp/qWl1S2wDb6pE6ds9uuSVUlxqJUKRSCnjjwC8vluUJZuAokEakdyH47HS3N0pVN8Vorvd6PyYfMWVyAZhEglYgbgVL78c9sHC/0g6NqrRZVapvEse9gRApPbn4jg/YMH6nToufUNJcrTVR0qRzI8TJujfftJX6dtNyOnLiWGh8LLAx4wGvbZ771/CfPs4S1nRd2qbaLJJVy3KFJ1qIm8tlpy6qZGWR1WSIHlWVd/LhdwYgWPnu2FbPfHOdVn8Hqm8N1DRz+4zEpYFpRuQjAWVT6njGR+I+en5eOtLzb62WheiVZIQJZPNlCsIySFbABBUlSM/8AiflqceOSdxbyUlnSxwU7gfdRn41+LfVVB1TXdKwTtQ0ERimSajYx1MqlFJTzNx2DcW5Vc/CB2JzDN6vLXXaahp5HRFjjDyswhVQMImSQIhlwqjGMjn009/FC1XLqqtl6utayXFUXbVCmTzRAFX+osnG3Hc+nOcYBMaJHJNIkMUTPI5CqqglmYngAfPTgZp2Q2Pa8amlfQARk40aftu8DfEOup/PeghpMnASdzuIwDn4AwHfsTnjto1XU3yj6x4Vy+k+lLl1Pe6272KiMtPV1cc9RJIg8hXVY4uWJww2IhKgZ+hzp433wA6o6iU1Fuq7LEtSgV6abfGgXGCPhQgkjuMev3lAsPjz0B0/0akN1uaW+OmgaJ5CSjE7dzABRu8w8/DjcSB66gfxm9uTrPqNZ+nPC2aawWo5R7lwK+oUqQQp5EAycgqfMyqsHXJXWW1k87/QKA8qPaKKb3U9hnsPUFz6culXRzVVrqpaOpakm82LzI2KtsYgEjIPBAYYwQpyNNyWimNHJLLGBkqNpx2z6/h+WmD0z1HLb6aaikWWZQfMiRDzkkbh/n8TpSN2rqlZPIEcKykttALMD8jjjONKyYTo5D4Xp8XMbLG39VdkqW+eeKulpZ1KAKWVh6/Q8a83WtVYmYqgCgnI9ABnTdW/XCnkMElMsrHjKkg/n/trTv1zaQ+6xOdrANJ9vy0dmG4yAlAyMxjYzXKTloq+oZStNMQ4ypKkDH2njGlvpOruXTd4o7wtBDWwpLiaklZdsqdmU5yMkHg84POvVFOtTaY8ABoRtPPJGMf41jDsrKFGASSPQ69GIm18rxpypNRFcK7fRfRnTlwmt/WFjSIwVVDJBE0KeWjIzo4JXaCGBTGDjG5gwz/TIAsAGC8ETbe5KZ+fb9e/y1W32VvEutTqyDoG4zE012gkraNWBLe9ooaRBgfCDErMS3GY+ME4NvUoWZQ24kE5DNgHt2/XWPLF0XloKbbJ1GhxTBuVgEko2qEwvAGM6R6iz7AokQBe2R3+uTgfnqTRbo4xgjJ5/qYsc5z3OT8v00nVlqyF8sKqgHODjk/v7tVAC4mio6/gkH96j/wBs5/LOjTya0REhVDqEG3C7QP00akkhdz2XNa89QXi9yL/E6+WcRgBFZjtXgDgdgeBk+uNJujRrSO2yuF6ido5FdDgg8HTtV3mpInd2yVVuDjkgevfRo0lljgrU/DiQTSTbgzDzZNxLKcZP00hMSWJJySedGjRMf2oeeSXBKVmkbfJET8O3fj6636liqhwBlSSPwOjRrRb7AvPTfnLVhvdysXUFFerTUCCstVRFVUkmxWEcsbBkbawKnBA4IIOORrqjukkmijWQxr5i7toHxjJ4OQePswfro0aRy05GBpCKynjnEau0q8hsxysh7Z7qRkcdjxrBURxFxuiVjC2ULDJBz3+3Ro0oFw3SZVpF5inyU5XPb6nRo0alvC6l/9k=","type":"message","user":"6282213542319@c.us"}

**App information (please complete the following information):**
 - Version  6.0.1
 - OS: 15.2

**Comment by vasani-arpit** [comment]
WBOT will send base64 string of the media. You need to convert it to image programatically. copy paste the string in here https://codebeautify.org/base64-to-image-converter and you can see the image.
