### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by zullvansugiantoro** [vasani-arpit/WBOT#138]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]
 - additional info which might be useful to reproduce the issue

**Additional context**

**Comment by pavanmehta91** [comment]
Closing the issue since Info is missing.
