### ISSUE TITLE
Cant open pdf files

### ISSUE THREAD

**Issue by cidocamp0s** [vasani-arpit/WBOT#142]
I am  trying to send PDF files using 
window.WAPI.sendImage('data:file/pdf;base64, my file','55xxxxxxxxxxx@c.us','test.pdf',''), the file wont open on android, but it opens on PC. 

following the logic, it works with audio like mp3 and video like mp4.
![image](https://user-images.githubusercontent.com/24815351/82170861-0e45d880-989c-11ea-9971-be466035d6a7.png) 
What am i doing wrong?

**Comment by tpjezy** [comment]
chenge data:file/pdf;base64 **to** data:application/pdf;base64

**Comment by cidocamp0s** [comment]
> **change** data:file/pdf;base64 **to** data:application/pdf;base64

Thanks
