### ISSUE TITLE
Some one can do something about this buttoms? Thanks

### ISSUE THREAD

**Issue by klaustokin** [vasani-arpit/WBOT#143]
I,m from mexico.
I,m not and expeert in your program.

Maybe some one can do this for Wbot.

Thanks 
Regards

https://developers.facebook.com/docs/whatsapp/message-templates/sending

**Comment by vasani-arpit** [comment]
This is not supported for now. will revisit this once this is available in [WAPI.js](https://github.com/mukulhase/WebWhatsapp-Wrapper/blob/master/webwhatsapi/js/wapi.js)
