### ISSUE TITLE
Send Received file/image to webhook

### ISSUE THREAD

**Issue by tradename** [vasani-arpit/WBOT#149]
How can i foward a file that a user has send to my webhook in base64...

If a user user sends a pdf how can i foward it to my webhook

**Comment by oOHiyoriOo** [comment]
u should be able to get the base64 code in msg object so u only have to convert it to a file since somewhere in the msg object the filetype is sepecified....
iam because iam doing something similar iam going to look into it and msg again if i find a solution! 
as far i know...

**Comment by igoeneo** [comment]
Add/Modify in WAPI.js

`window.WAPI.downloadFile2 = async function(url, done) {
    let xhr = new XMLHttpRequest();
    xhr.onload = function () {
        if (xhr.readyState == 4) {
            if (xhr.status == 200) {
                done(xhr.response);
            } else {
                console.error(xhr.statusText);
            }
        } else {
            console.log(err);
            done(false);
        }
    };
    xhr.open("GET", url, true);
    xhr.responseType = 'arraybuffer';
    //xhr.responseType = 'blob';
    xhr.send(null);
};`

Add identifier for your media file. Actually I add this for response only the media files. If its text, your "else" is the original one.
`body.isMMS = message.isMMS;
		body.caption = message.caption;
		if(body.isMMS){
			WAPI.downloadFile2(message.clientUrl, function(result) {
				Store.CryptoLib.decryptE2EMedia(message.type.toLowerCase(), result, message.mediaKey, message.mimetype).then(function(a) {
					let reader = new FileReader();
					reader.onload = function (e) {
						window.log("reader.result is" + reader.result); //for checking, is it working
						body.text = reader.result;
						var fmtText = {
							method: "POST",
							body: JSON.stringify(body),
							headers: {
								'Content-Type': 'application/json'
							}
						}
						if (intents.appconfig.webhook) {
							fetch(intents.appconfig.webhook, fmtText)
							.then((resp) => resp.json()).then(function (response) {
								//response received from server
								console.log(response);
								WAPI.sendSeen(message.chatId._serialized);
								//replying to the user based on response
								if (response && response.length > 0) {
									response.forEach(itemResponse => {
										WAPI.sendMessage2(message.chatId._serialized, itemResponse.text);
										//sending files if there is any 
										if (itemResponse.files && itemResponse.files.length > 0) {
											itemResponse.files.forEach((itemFile) => {
												//WAPI.sendImage(itemFile.file, message.chatId._serialized, itemFile.name);
												//window.log(getFile(itemFile.file));
												window.getFile(itemFile.file, itemResponse.tempatFile).then((base64Data) => {
													//console.log(file);
													WAPI.sendImage(base64Data, message.chatId._serialized, itemFile.file);
												}).catch((error) => {
													window.log("Error in sending file\n" + error);
												})
											})
										}
									});
								}
							}).catch(function (error) {
								console.log(error);
							});
						}
					};
					reader.readAsDataURL(a._blob);
				}).catch(function(e) {
					window.log("Error: " + e);
				});
			});
		}`

Receive it in webhook in index.js
`async function (req, res, next){
		var check = req.body.text.split(":");
		if(check[0].toLowerCase() == 'data'){
			var wftl = check[1].split(",");
			var pathDownload = "X:\\Shared drives\\Probo's\\wbot\\";
			var fileDownload = pathDownload + req.body.caption ;
			fs.writeFile(fileDownload, wftl[1], 'base64', function(err) {
				 if (err) throw err;
				console.log('Download!');
			});
			res.send([{
			  "text": req.body.caption + " downloaded!",
			  "type": "message"
			}])
		}
		else next()
	}`

Hope this will help.
