### ISSUE TITLE
Spintax syntax in reply

### ISSUE THREAD

**Issue by vasani-arpit** [vasani-arpit/WBOT#15]
something like this http://spintaxtool.appspot.com/

**Comment by chprasad893** [comment]
Submitted pull request for this feature #65

**Comment by lucas-engen** [comment]
@vasani-arpit this issue can be closed. The PR #65 was merged

**Comment by vasani-arpit** [comment]
> @vasani-arpit this issue can be closed. The PR #65 was merged

Thanks. Closing.
