### ISSUE TITLE
Fantastic

### ISSUE THREAD

**Issue by bozdoz** [vasani-arpit/WBOT#151]
Just a note to say this is a fantastic app. 👏 

I was surprised to find out that it in fact **works** in headless mode! 

I've ran into issues in my project https://github.com/bozdoz/hey-now

I've also seen issues on the puppeteer repo related to this: https://github.com/puppeteer/puppeteer/issues/921

I'm guessing you solved this issue by using `puppeteer-core` as opposed to `puppeteer`?

Anyway, thanks for this! 😄

**Comment by bozdoz** [comment]
Or maybe the chrome version is the key: `666595`; either way.  Good to see a working solution!

**Comment by mikelpr** [comment]
care to share what was the solution? I am running into the issue myself :(

**Comment by bozdoz** [comment]
@mikelpr I wrote it in the comments above: either puppeteer-core or chrome 666595, or both.  Check out the code at https://github.com/bozdoz/hey-now

**Comment by bozdoz** [comment]
@mikelpr Actually now that I've revisited my project, I'm realizing it no longer works in headless mode.  Not sure what changed.

**Comment by vasani-arpit** [comment]
There is two key things one being stable chromium.  beta or canary channels won't work. another is UserAgent. 

This should sort your issue out. Let me know if you want me to check your repo and fix it I could.
