### ISSUE TITLE
Qrcode in windows

### ISSUE THREAD

**Issue by indragunawan82** [vasani-arpit/WBOT#153]
![image](https://user-images.githubusercontent.com/9045625/89706818-52c0ac00-d993-11ea-9cf2-45dcc3951bf7.png)

In windows, my qrcode become like attached. what is the solution for this?

**Comment by indragunawan82** [comment]
Fyi .. i use nodemon

if i use node index.js 

it will work

**Comment by prakhargurunani** [comment]
@indragunawan82 Does it work in powershell ?

**Comment by indragunawan82** [comment]
i havent try in powershell, my goal is on linux

**Comment by prakhargurunani** [comment]
@indragunawan82 It seems there is an issue with `nodemon` and it is just displaying raw QR code data. When you start a fresh server instance for first time with nodemon...does it work correctly ?

**Comment by indragunawan82** [comment]
not working also

not only nodemon, if i run node src/index.js also gives error

if i got that error, then it will always error

Thanks
IG

**Comment by vasani-arpit** [comment]
This must be mixup due to font or something. I have windows and I am not facing this issue. Please provide more details to reproduce. closing until we receive further info.
