### ISSUE TITLE
Implement Webhook

### ISSUE THREAD

**Issue by Masagung0805** [vasani-arpit/WBOT#159]
please help me.. i need step by step use webhook
can you show the file or script example

**Comment by Masagung0805** [comment]
**i try webhook with PHP but no reply from webhook**

- [ ] Step 1 Create **test.php**
```
<?php
header("Content-Type: application/json");
header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type,Accept");

$x = file_get_contents("php://input");
$x = json_decode($x);
$message = $x->text;
$msg_typ = $x->type;

//$response = array(array('text' => '', 'type' => $msg_typ));


    switch($message) {
	
case 'coba':
	//$response = array(array('text' => 'hello my dear friend', 'type' => $msg_typ));
	$response =array('text' => 'berhasil' ,'type' => 'message');
    $response = json_encode($response);
    echo($response);
}
?>
```

- [ ] STEP 2 modify **bot.json**

`"webhook": "http://mydomain.com/tes.php"`

**Comment by z3nth10n** [comment]
Why do you support Express JS webhooks only? There isn't any way to use PHP webhooks?

**Comment by prakhargurunani** [comment]
@vasani-arpit It seems PHP Webhooks are not working for others users too. Can you suggest some solution since I am not experienced in PHP.

**Comment by peter-id** [comment]
Yesterday i try to using php webhook and work, but today its doesnt work anymore, no changes on settings, dunno why
