### ISSUE TITLE
Bot not working (not detecting received messages)

### ISSUE THREAD

**Issue by N-MHash** [vasani-arpit/WBOT#166]
**Description**
No messages are being detected at all, therefore no messages are being responded to.
```
v0.13.0
√ Downloading chrome ... done!
√ Launching Chrome ... done!
√ Opening Whatsapp ... done!
√ Looks like you are already logged in
WBOT is ready !! Let those message come.
```
and that's it, no messages are detected nor responded to. As if `WAPI.waitNewMessages()` is not being called, or no data is being read from WhatsApp.

**To Reproduce**
`node src\index.js` 

**Expected behavior**
To read a received message ("hi", "hello") or otherwise.
To print on console that a message has been received from `chatId` and the `response` to be sent.
To respond accordingly with `response` (per `bot.json` file).

**App information**
 - Version 0.12.8 and 0.13.0
 - npm updated and puppeteer-core installed

---

Where is it going wrong? I am unable to troubleshoot. It should work as expected, but it's not.

**Comment by swandono** [comment]
This worked for me. https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051

**Comment by FitterX** [comment]
I have trouble too!
Stop work! :(

**Comment by swandono** [comment]
@FitterX Minor changing wapi.js should've done it.
https://github.com/open-wa/wa-automate-nodejs/commit/f4cc51423aa367ad3c7b735a799d6f7d6ab05051

**Comment by klaustokin** [comment]
I have the same Problem.....  
Help! Thanks

**Comment by senokrn** [comment]
I have the same Problem.....
Help! Thanks

**Comment by swandono** [comment]
Guys? @klaustokin  @senokrn 

Delete
`{ id: "bp", conditions: (module) => (module.default&&module.default.toString().includes('bp_unknown_version')) ? module.default : null },`
Add
`{ id: 'Perfil',conditions: (module) => module.__esModule === true && module.setPushname && !module.getComposeContents? module  : null,},`

Change
`    if(!Store.Versions.default[12].BinaryProtocol) Store.Versions.default[12].BinaryProtocol=new Store.bp(Store.Me.binVersion);
    return await Store.Versions.default[12].setPushname(newName);`
To
`return await window.Store.Perfil.setPushname(newName);`

**Comment by senokrn** [comment]
Thanks @swandono

**Comment by wichyalonzo** [comment]
Hello to all colleagues, excuse me, I also have the problem, it will be that someone of you can tell me the instructions on how to fix it 😥 thank you very much to anyone who helps me

**Comment by compuarc** [comment]
Hi, please instructions to repair this issue in Linux

**Comment by vasani-arpit** [comment]
Thank you @swandono 

@compuarc @wichyalonzo @klaustokin @FitterX @N-MHash 
A new version has been released. Please download the latest binary or pull the master branch.
