### ISSUE TITLE
Importing a module into inject.js

### ISSUE THREAD

**Issue by N-MHash** [vasani-arpit/WBOT#169]
Is there a way possible to import nodejs `fs` File System module into `inject.js` to be able to run code on image/pdf files before using `WAPI.sendImage` function?

**Comment by vasani-arpit** [comment]
No. As it is a browser we can't import node modules there. But we can send over the data in base64 strings. the code to send the file to the browser and recipient is already there. 

Try to run the code without changing bot.json and send the message `github`  bot should reply with image as per the last rule written in bot.json. you can also mention pdf file as well.

**Comment by N-MHash** [comment]
Understood. I take there is no way to run operations that require node modules before executing browser commands?

What I specifically want to do is read the message received, query and match its content locally (a database) and then check the state of a file (date modified, for example), then upload it.

I am unaware of a workaround. If you happen to have another approach on how to accomplish that, could you enlighten me?

**Comment by vasani-arpit** [comment]
You can use webhook for that. Every time new message is arrived webhook URL will be called with all the necessary details in the payload. 

So you just need to make a backend application in any language which will listen to the requests coming from WBOT and respond after communicating with db. 

here is the docs and example for webhook https://github.com/vasani-arpit/WBOT/blob/master/docs/Webhook-example.md

**Comment by N-MHash** [comment]
I was able to achieve what I wanted by adding the functions I needed in `utils.js` using Promises then using
`page.exposeFunction` to be able to use these functions within a page context.
