### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by indragunawan82** [vasani-arpit/WBOT#172]
![image](https://user-images.githubusercontent.com/9045625/94998569-d89c5480-05dc-11eb-9caa-9ac6206443ba.png)

if i stop nodemon, and run again ... sometime it works, sometime shown like image above...why its unstable?

**Comment by prakhargurunani** [comment]
Forcefully closing the nodemon server without logging out may cause this error.

**Comment by prakhargurunani** [comment]
@vasani-arpit can I add this in the docs ?

**Comment by indragunawan82** [comment]
how is the way so  this will not happen? specially in development mode, not production

**Comment by prakhargurunani** [comment]
Sometimes this works -- `npm cache clean`

**Comment by prakhargurunani** [comment]
@vasani-arpit @indragunawan82 I have created a PR for it --> #174

**Comment by vasani-arpit** [comment]
Okay. Thanks. 
Checking the PR.

**Comment by prakhargurunani** [comment]
> Okay. Thanks.
> Checking the PR.

Can you also please add `Hacktoberfest` topic to the repo...a very small request....as I am participating in it. The repo in which i am contributing must have it as a topic

**Comment by indragunawan82** [comment]
![image](https://user-images.githubusercontent.com/9045625/95023589-1b772e80-06a8-11eb-8cb9-e229679264ba.png)



npm cache clean -> not working on me, tried many times

**Comment by prakhargurunani** [comment]
It had worked in my case....without any errors....on 2 machines. Are you continously getting the above error or just frequently?

**Comment by indragunawan82** [comment]
before this, i run script successfull, but after i restart pm2, it happened again,also i run node manually by calling the file, stil same

even i ran npm cache clean before

**Comment by prakhargurunani** [comment]
Does it give error when launching through the `windows` option ?

**Comment by indragunawan82** [comment]
u mean , if run this in windows? -> linux more frequent
or windows option u mean is using headless = false? -> less frequent

**Comment by prakhargurunani** [comment]
> u mean , if run this in windows? -> linux more frequent
> or windows option u mean is using headless = false? -> less frequent

Yes

**Comment by indragunawan82** [comment]
not error after i pull, previous yes
my goal is on linux

**Comment by prakhargurunani** [comment]
@vasani-arpit Any update ?

**Comment by indragunawan82** [comment]
@prakhargurunani  @vasani-arpit    is there any update , its been  a while

**Comment by prakhargurunani** [comment]
@indragunawan82 As #153 is also caused due to `nodemon`, it is recommended to use `node` for now until it gets fixed.

**Comment by indragunawan82** [comment]
how i can run "node" command only in the background?
if i close putty, then node will be closed rite?

Thanks
IG

**Comment by prakhargurunani** [comment]
`nodemon` simply re-runs your server if any changes occur, whereas `node` does not. Are you using SSH ?

**Comment by indragunawan82** [comment]
yes, using SSH

if i close terminal, then node will stop
any advice ?

Thanks
IG

**Comment by prakhargurunani** [comment]
@indragunawan82 This can only happen when you run the bot by SSHing into VPS and running it through that terminal. As you close SSH connection, terminal also closes. Install GUI for your Linux distribution and then open terminal.

**Comment by vasani-arpit** [comment]
@indragunawan82 if you have a VPS then installing a GUI would be a very long way to do things. I think pm2 is the suitable option. I have seen other people use it for months without any interruptions. Let me know if you want me to take a look into the server.

**Comment by indragunawan82** [comment]
Installing GUi is not an option for me,because i need server still in low
usage of resource.

I always using pm2,my problem also happen even using pm2

**Comment by vasani-arpit** [comment]
As I mentioned earlier. Other people are using it via pm2 and they are not facing any issue at all. are you using ecosystem in pm2 ? 

others are using that. I think it helps. 

Reopen if needed.
