### ISSUE TITLE
Contains being ignored while no noMatch

### ISSUE THREAD

**Issue by Obandito** [vasani-arpit/WBOT#173]
When you leave noMatch empty ("noMatch": [] or "noMatch": false) it respondes nothing, which is fine. But it also ignores contains. I tested ("noMatch": ""). After doing and restarting contains functions but it reads all Messages.

![WBOT replied](https://user-images.githubusercontent.com/72341833/95015136-abd35600-064b-11eb-88bf-5ca471df32ae.PNG)

Is there a way, don't having any noMatch?

**App information (please complete the following information):**
 - Version [v0.13.1]
 - OS: [Windows. It will be Ubuntu soon.]

**Comment by prakhargurunani** [comment]
@Obandito Do you mean you want the bot not to read message when there is a `noMatch` situation ?

**Comment by Obandito** [comment]
Jeah, it shouldn't ignore conains and exact Matches if you leave noMatch empty.

**Comment by prakhargurunani** [comment]
`contains` and `nomatch` are tested first. If no match is found, `nomatch` is the only last option. So,if it is empty, no replies are expected.

**Comment by Obandito** [comment]
Am I leaving it empty wrong? In my Case it did't check Partial Matches first.

**Comment by Obandito** [comment]
I removed the else for noMatch because i don't need it and now it works finde for me.

**Comment by prakhargurunani** [comment]
> Am I leaving it empty wrong? In my Case it did't check Partial Matches first.

yes..it should not be empty.

**Comment by Obandito** [comment]
Okay. So there is no way leaving it empty right? / Having no noMatch Situation?

**Comment by prakhargurunani** [comment]
> Okay. So there is no way leaving it empty right? / Having no noMatch Situation?

It is a `required` variable, as it is the only last option when no `exact` or `contains` matches. So it can't be empty.

**Comment by Obandito** [comment]
Okay, thanks!
