### ISSUE TITLE
Using an external chrome extension within the chrome/puppeteer session created?

### ISSUE THREAD

**Issue by N-MHash** [vasani-arpit/WBOT#175]
I was able to load an extension by adding the following arguments:
```js
/** constants.js */

this.DEFAULT_CHROMIUM_ARGS = [
    ...
    ...
    "--disable-extensions-except=path/to/extension_directory", // <----- added
    "--load-extension=path/to/extension_directory"             // <----- added
];
```
But this causes the script to create/launch two windows.

The first window is the default WBOT's puppeteer session(?) [without an address bar, back/forward/refresh, extensions, etc...]

The second window is a normal Chromium browser window with the address bar, the extension loaded and everything like a normal browser. With none of WBOT features working.

Ideas as to what causes that to happen, and how to make it work?

**Comment by N-MHash** [comment]
As far as I've got:
I removed the following line:
```javascript
constraints.js

`--app=${WHATSAPP_WEB_URL}`,
```
Which allowed me to have the two windows infused in one, with two tabs instead and the extension enabled. The workaround is to just close the second tab and have the bot working on the first.

Still looking for a better way if anyone knows of one.

**Comment by prakhargurunani** [comment]
@N-MHash Maybe `--load-extension=path/to/extension_directory` just opens WBOT in second full fledged window but we have only one server instance running at that time...which would connect to 1st window where originally WBOT is working...So it would load just the frontend in 2nd window and JS requests would not reach the server.

A workaround for now is to not use `--load-extension` method after if you are already using `--disable-extensions-except`.

**Comment by vasani-arpit** [comment]
Another thing we can do is instead of adding extensions into our puppeteer chrome we can connect to user's existing running chrome via simple http request. user just need to open the dev tools port. here is more info https://blog.chromium.org/2011/05/remote-debugging-with-chrome-developer.html

**Comment by vasani-arpit** [comment]
This is now available as feature in development branch.
