### ISSUE TITLE
Failing CI builds

### ISSUE THREAD

**Issue by prakhargurunani** [vasani-arpit/WBOT#183]
**Describe the bug**
The builds are failing, after @AkiaCode 's PR was merged. They have been reverted.

**Comment by prakhargurunani** [comment]
@tbs-arpit Have a look about what is breaking the builds.

**Comment by AkiaCode** [comment]
@prakhargurunani Sorry

**Comment by AkiaCode** [comment]
@prakhargurunani  I found error

https://github.com/vasani-arpit/WBOT/blob/3fea1539361e680f1249a858f9c24711adbd0b9a/package.json#L3

1.4.0 to 1.4.1

**Comment by prakhargurunani** [comment]
Make changes and open a new Pr. @AkiaCode

**Comment by AkiaCode** [comment]
Okay

**Comment by AkiaCode** [comment]
#184 @prakhargurunani
