### ISSUE TITLE
👥 Multiple instances 

### ISSUE THREAD

**Issue by antoniorrm** [vasani-arpit/WBOT#194]
How can I use WBOT on two computers but with a single number of wpp? It's possible?

**Comment by prakhargurunani** [comment]
@antoniorrm English please..

**Comment by antoniorrm** [comment]
> @antoniorrm English please..

sorry

**Comment by esteves67** [comment]
@antoniorrm Whatsapp with multiple instances in a single number you can check for https://github.com/canove/whaticket .

**Comment by antoniorrm** [comment]
> @antoniorrm Whatsapp com várias instâncias em um único número você pode verificar https://github.com/canove/whaticket .

Thanks for the info
