### ISSUE TITLE
Live bot.json reload.

### ISSUE THREAD

**Issue by vasani-arpit** [vasani-arpit/WBOT#20]
**Is your feature request related to a problem? Please describe.**
What if user changes bot.json while WBOT is running. will it pick up changes? no obviously. but What if it can? 

**Describe the solution you'd like**
May need to use file watching modules for this.

**Comment by andersondeoliveiramachado** [comment]
![image](https://user-images.githubusercontent.com/1152426/57708864-7128e200-7640-11e9-9ad1-74dd9035e102.png)

	async function checkJSON() {
		console.log("Verificando o JSON - INICIANDO - " + countJSON);
		
		let botjsoncheck = fs.readFileSync("bot.json");
		
		//console.log(md5(lastJSON));
		//console.log(md5(botjsoncheck));
		
		let diferente = (md5(lastJSON) != md5(botjsoncheck));

		//console.log(" json diferente = " + diferente );
		//console.log("\n\n\n");
		//console.log(lastJSON);
		//console.log(botjsoncheck);
		
		if(diferente) {
				
			lastJSON = botjsoncheck;
					
			console.log('Atualização do JSON realizada com sucesso.');
			
			var content = fs.readFileSync("bot.json", "utf8");
			console.log(JSON.parse(content));		
			
			page = await browser.pages();
			if (page.length > 0) {
				page = page[0];
				
				let botjson = utils.externalInjection("bot.json");
				
				botjson.then((data) => {
					page.evaluate("var intents = " + data);
					console.log(data);
				}).catch((err) => {
					console.log("there was an error \n" + err);
				});		
			} else {
				console.log("Impossível ler o conteudo da página.");
			}
			
		} else {
			console.log('Nenhuma mudança no JSON.');	
		}
		
		console.log("Verificando o JSON - CONCLUIDO - " + countJSON);
		countJSON = countJSON +1;
		
	}

**Comment by andersondeoliveiramachado** [comment]
SOLVED !!!!


var lastJSON = ''
var countJSON = 0;
var browser = null;
	
async function Main() {
.
.
.
        //const browser = await puppeteer.launch({
		browser = await puppeteer.launch({
            executablePath: revisionInfo.executablePath,
            headless: appconfig.appconfig.headless,
            userDataDir: path.join(process.cwd(), "ChromeSession"),
            devtools: false,
            args: constants.DEFAULT_CHROMIUM_ARGS, ...extraArguments, ...pptrArgv
        });
.
.
.

**Comment by vasani-arpit** [comment]
Use fs module. It would be easier and performance effective.

https://nodejs.org/docs/latest/api/fs.html#fs_fs_watchfile_filename_options_listener
