### ISSUE TITLE
VM58:1 Uncaught ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by eddysby2000** [vasani-arpit/WBOT#207]
**Describe the bug**
happen since Feb 25, 2021
**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]
 - additional info which might be useful to reproduce the issue

**Additional context**

**Comment by onjackstalbeck** [comment]
Change webpackJsonp  to webpackChunkbuild

**Comment by vasani-arpit** [comment]
Thank you for reporting. issue has been resolved in latest version. v0.15.1
