### ISSUE TITLE
check number status always TRUE

### ISSUE THREAD

**Issue by cidocamp0s** [vasani-arpit/WBOT#208]
![image](https://user-images.githubusercontent.com/24815351/109248060-dc1abd00-77c3-11eb-863f-264abe42c0ef.png)

CheckNumber function always returns TRUE, as the image above shows.

The original return was a 404 NOT FOUND if the number havent whatsapp or 200  if the number  has a valid whatsapp.

how to solve this issue?

**Comment by vasani-arpit** [comment]
use callback to get the results

```javascript
WAPI.checkNumberStatus("XXXXXXXXXX@c.us",function(){console.log(arguments[0])})
```
