### ISSUE TITLE
Get name

### ISSUE THREAD

**Issue by CactusWingsMX** [vasani-arpit/WBOT#210]
Could you implement the function to get the name of the person who sends a message to the Bot?

**Comment by vasani-arpit** [comment]
Yes. that is possible but the messages are coming from `bot.json` there will be a need of updating variable in a string.

**Comment by vasani-arpit** [comment]
can use something like this https://stackoverflow.com/a/18234317/2983629

**Comment by vasani-arpit** [comment]
This feature has been implemented in version v0.16.0

**Comment by CactusWingsMX** [comment]
Thank you very much indeed, it is something you need <3
