### ISSUE TITLE
messageObject = messageObject.valueOf() ???

### ISSUE THREAD

**Issue by AngusFan-GH** [vasani-arpit/WBOT#214]
https://github.com/vasani-arpit/WBOT/blob/267188b115a25b5c655ade2c6579d4da1d94e091/src/WAPI.js#L696

**Comment by vasani-arpit** [comment]
Please explain what seems to be the problem?

**Comment by AngusFan-GH** [comment]
When I try to call the WAPI.ReplyMessage function，there will throw an error like "messageObj.value is not a function", may be you should use "vuleOf" instead of that. But after fixing this, it still wrong because of WhatsApp updating. On 03/31/2021 16:05, Arpit Vasani wrote: 
Please explain what seems to be the problem?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/vasani-arpit/WBOT/issues/214#issuecomment-810865881",
"url": "https://github.com/vasani-arpit/WBOT/issues/214#issuecomment-810865881",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by vasani-arpit** [comment]
Make sure you are using latest version of WBOT.
