### ISSUE TITLE
WAPI.getMe() doesn't work.

### ISSUE THREAD

**Issue by jasp402** [vasani-arpit/WBOT#222]
Greetings friends, I was reviewing some of the functions and I wanted to see what data `WAPI.getMe()` brings me. But it shows me an error.

`Cannot read property 'all' of undefined`
![image](https://user-images.githubusercontent.com/8978470/115336157-3d2b9500-a164-11eb-9f39-e5b1e55c94f6.png)

I have reviewed the function a bit and solving it was not quite simple. I'll leave the solution here for you to review and test yourself. I thought about simplifying it a bit but this way it is better so that it looks very similar to the previous one.

```js
window.WAPI.getMe = function (done) {
	const rawMe = window.Store.Contact.get(window.Store.Conn.wid._serialized);
	
	if (done !== undefined) done(rawMe);
	return rawMe;
};
```

![image](https://user-images.githubusercontent.com/8978470/115336701-49642200-a165-11eb-85f4-be2a64ebcc35.png)

it would finally look something like this
![image](https://user-images.githubusercontent.com/8978470/115336841-8defbd80-a165-11eb-8794-b5331c5eea94.png)

**Comment by vasani-arpit** [comment]
This is resolved in latest version along with other features. Test it out and let me know. ✌
