### ISSUE TITLE
Contains is not working for me

### ISSUE THREAD

**Issue by Diego-Schmidt** [vasani-arpit/WBOT#224]
"contains": ["word1","word2"], is not working in my WBOT installation. Bot is not replying to key words. "exact" is working fine.

**Comment by vasani-arpit** [comment]
Will test and get back to you.

**Comment by ItHustleCoder** [comment]
> "contains": ["word1","word2"], is not working in my WBOT installation. Bot is not replying to key words. "exact" is working fine.

Hi, Diego-Schmidt
Can you show your **bot.json** file ? In my projects, I use either contains or extra for a specific event , I **do not use both of them for one operation**.
It's work for me:
Try to separate words between using "|" 
`"contains":["hello|hi|ciao"],
"exact":[],  - must be empty,
"response": "Hi, how are you?"
` ,
Let me know if it helped
I will run tests

**Comment by Diego-Schmidt** [comment]
Contains is in the format that came with the default bot.js file. 
 {
            "contains": ["janmdin","hardik","shubhkaamna"],
            "exact": [],
            "response": "aabhar 🙏"
        },

**Comment by Diego-Schmidt** [comment]
I have tested the bot with a clean bot.json and containst is working @_@ I don't know what error caused the bot to stop working.

**Comment by vasani-arpit** [comment]
Closing this for now. Feel free to open if it happens again.
