### ISSUE TITLE
Forward Messages

### ISSUE THREAD

**Issue by shajji1** [vasani-arpit/WBOT#225]
Can you please add this feature, it will be helpful to send any type/media of message.

**Comment by vasani-arpit** [comment]
@shajji1 Please provide a use case for this one.

**Comment by Diego-Schmidt** [comment]
I think he is asking for a command to send messages and media using the bot, to avoid direct contact with clients or something like that.

**Comment by vasani-arpit** [comment]
@shajji1 Closing this for now as there is no real use case to this.
