### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by merco** [vasani-arpit/WBOT#228]
**Get files from input data**
It would be possibile to get files from JSON input data?
something like  
` "files":[{
      "name":"Name of the file",
      "file":"<Base64-string-of-the-file>"
  }]`

**Comment by vasani-arpit** [comment]
Yes. that would be nice to see. Will add that in upcoming release.

**Comment by vasani-arpit** [comment]
not stale.

**Comment by vasani-arpit** [comment]
will work on this.

**Comment by vasani-arpit** [comment]
not stale.

**Comment by vasani-arpit** [comment]
Not stale

**Comment by vasani-arpit** [comment]
Fixed in [latest](https://github.com/vasani-arpit/WBOT/releases/) release
