### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by rajeshkumaryadavdotcom** [vasani-arpit/WBOT#230]
Windows 10 Node JS

after npm install when running node src/index.js then getting below error

$ node src/index.js
module.js:550
    throw err;
    ^

Error: Cannot find module 'C:\Users\rajesh\Desktop\ng\node\WBOT-master\src\index.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by vasani-arpit** [comment]
Make sure you do `npm install` before doing `node src/index.js`

**Comment by rajeshkumaryadavdotcom** [comment]
As I mentioned earlier, I have already done that

**Comment by vasani-arpit** [comment]
I need to see exactly what is happening on machine. setup a quick call with me using following link.

https://calendar.x.ai/arpitvasani/quickcall

**Comment by vasani-arpit** [comment]
@rajeshkumaryadavdotcom Please respond or close.
