### ISSUE TITLE
Oden de archivo 

### ISSUE THREAD

**Issue by dimare500** [vasani-arpit/WBOT#231]
Hello I want to congratulate you on your Bot is great.

I have been playing with your bot and I want the image to load first and then the answer but it always does it in reverse, answer and then image. Can you place image and then answer? Another thing can you send images with a comment?

**Comment by dimare500** [comment]
Hello I want to congratulate you on your Bot is great.

I have been playing with your bot and I want the image to load first and then the answer but it always does it in reverse, answer and then image. Can you place image and then answer? Another thing can you send images with a comment?

**Comment by dimare500** [comment]
> Hola quiero felicitarte por tu Bot esta genial.
> 
> He estado jugando con el y quiero q la imagen cargue primero y luego la respuesta pero siempre lo hace al reves, respuesta y lueo imagen. ¿Se puede puede colocar imagen y luego respuesta? Otra cosa se puede enviar imagnes con un comentario ?

**Comment by vasani-arpit** [comment]
> Can you place image and then answer?

Can't do that because image upload time may be different. It depends on a size of the image and also internet.

>Another thing can you send images with a comment?

I think you mean image with caption. yes. it can be done. Will add this feature in upcoming release.

**Comment by vasani-arpit** [comment]
not stale.

**Comment by vasani-arpit** [comment]
Not stale

**Comment by vasani-arpit** [comment]
Fixed in [latest](https://github.com/vasani-arpit/WBOT/releases/) release
