### ISSUE TITLE
Message doesn't captured

### ISSUE THREAD

**Issue by erzqy** [vasani-arpit/WBOT#240]
I use the latest version of master branch.

Since today WAPI.js doesn't working anymore and didn't throw any error.

**Comment by Markiz2020** [comment]
Yeah getting the same error 
`(node:69928) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: WAPI is not defined
    at __puppeteer_evaluation_script__:1:1`

**Comment by imkhubaibraza** [comment]
I'm getting the same error when I try to send the message.
`(node:69928) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: WAPI is not defined`

**Comment by vasani-arpit** [comment]
Looks like there is a new WA update. which WA version you are on? you can check it from Settings > Help

**Comment by gmtandi** [comment]
by here not working too... version 2.2126.10

**Comment by vasani-arpit** [comment]
Issue has been fixed. Please try the latest release. https://github.com/vasani-arpit/WBOT/releases version 0.19.1

**Comment by erzqy** [comment]
Issue closed.
