### ISSUE TITLE
New Multi-Device beta

### ISSUE THREAD

**Issue by chalfling** [vasani-arpit/WBOT#245]
I think will be cool if implement this feature.

New Multi-Device Beta need it to read **TWO** QR-Code

Thank you!

**Comment by vasani-arpit** [comment]
I think once it is generally available, I can look into it or someone will make a PR for it. For now I don't have enough devices to thoroughly test it.

**Comment by chalfling** [comment]
Hello @vasani-arpit now Multi-Device is mandatory

**Comment by vrushalipachchigar** [comment]
refer to #321 for further details
