### ISSUE TITLE
Question / Feature request

### ISSUE THREAD

**Issue by djebbe** [vasani-arpit/WBOT#258]
Hey,
first of all. i love this program! it works amezing!

is there a way to read text from a txt file or webpage and put it in a message as clear text instead of putting a file?

Greets

**Comment by vasani-arpit** [comment]
Glad to see WBOT being useful to you. 

For your use case, you can use webhook feature. 

If you don't have hosting/server to host your webhook app then you can use google sheets with Google App script webapp and connect it via webhook property in bot.json

**Comment by djebbe** [comment]
> Glad to see WBOT being useful to you.
> 
> For your use case, you can use webhook feature.
> 
> If you don't have hosting/server to host your webhook app then you can use google sheets with Google App script webapp and connect it via webhook property in bot.json

okay thanks ill try that!
