### ISSUE TITLE
Improve the smartreply feature

### ISSUE THREAD

**Issue by nikhilmaske-2001** [vasani-arpit/WBOT#273]
**Is your feature request related to a problem? Please describe.**
This should be valid only when `smartreply` is true and `clicktosend` is true:
When you click on anysuggestion it will be sent instantly (after merging #271).
When the input field contains some text and click on any suggestion it will send `input field text + smartreply`. We want to enhance this features by first clearing the input field and send only smartreply, and then again recover the old input field text.

**Comment by vasani-arpit** [comment]
#271 has been merged.
