### ISSUE TITLE
WBOT does not work after a refresh

### ISSUE THREAD

**Issue by nikhilmaske-2001** [vasani-arpit/WBOT#279]
**Describe the bug**
1. WBOT does not work after a refresh ([Solution](https://github.com/vasani-arpit/WBOT/issues/279#issuecomment-962495788))
2. WBOT does not work if we respond to the loaded whatsapp web page and WBOT is still loading in the terminal due to [this](https://github.com/vasani-arpit/WBOT/blob/master/src/index.js#L151). So we need to avoid using `delay`, instead use something which is more interactive with the chromium page,

**To Reproduce**
Steps to reproduce the behavior for 1:
1. Start `WBOT`
2. Refresh the whatsapp web page (chromium)

Steps to reproduce the behaviour for 2:
1. Start `WBOT`
2. Respond (open/click anything) to whatsapp web page (opened in chromium) while WBOT is still loading in the terminal 
(Note: This might be the case that page tooks more than 10 sec and you will not be able to perform step 2)

**Comment by vasani-arpit** [comment]
We need to find an event in puppteer if there is any which could detect page refresh. Once that is triggered we will reinject the WAPI.js and other necessary files.
