### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by ghmarko** [vasani-arpit/WBOT#286]
iam trying to use WAPI.js but that give me:
 Uncaught ReferenceError: webpackJsonp is not defined 
and second error is :
 Cannot read properties of undefined (reading 'Msg')
how to solve these erros

**Comment by vasani-arpit** [comment]
Which version of wbot you are using?

**Comment by rpsoftech** [comment]
Replace webpackJsonp with webpackChunkwhatsapp_web_client..
It Should Work Fine
