### ISSUE TITLE
Online contacts Notifications

### ISSUE THREAD

**Issue by Abhaydevka** [vasani-arpit/WBOT#293]
when any of our contacts come online we'll get a notification inside the app, which should be triggerable.
This would come in handy in many situations, for example, if we send a message to a contact and it's too boring to just wait staring at the screen for them to come online, so I think it would be great if we get a notification about them coming online, so that we can stop whatever we are doing and go and chat with them. And many other situations..
Thankyou.

**Comment by vasani-arpit** [comment]
This is nice. It can be done. I have seen this some where. There is a limit from WA side on how much contacts we can track. 

_What is the reason to close this issue?_
