### ISSUE TITLE
Sendmsg and sendmessagetoID

### ISSUE THREAD

**Issue by tradename** [vasani-arpit/WBOT#294]
Function's sendmessage('Number@c.us','my message's) and sendmessagetoID seem not to be sending to contacts that have not been recently contacted. It's also not sending to contacts saved in phone .

**Comment by vasani-arpit** [comment]
have you tried sendMessage2 function? It might work !!

**Comment by tradename** [comment]
sendmessage2 won't work again,   

**error message**

/snapshot/master/src/WAPI.js:307 Uncaught TypeError: Cannot read property 'sendMessage' of undefined
    at Object.window.WAPI.getChat (/snapshot/master/src/WAPI.js:307)
    at Object.window.WAPI.sendMessage2 (/snapshot/master/src/WAPI.js:829)
    at <anonymous>:1:6

**Comment by vasani-arpit** [comment]
have a look at inject.js https://github.com/vasani-arpit/WBOT/blob/master/src/inject.js#L212 ```sendMessage2``` is being used in all places there. If your bot responds then ```sendMessage2``` is working.
