### ISSUE TITLE
Fix image download issue

### ISSUE THREAD

**Issue by vasani-arpit** [vasani-arpit/WBOT#296]

**Comment by vasani-arpit** [comment]
as per discussion in #295

**Comment by GonzaloAndrade** [comment]
Hello! Found anything?

**Comment by vasani-arpit** [comment]
Yes. will add a fix over this weekend.

**Comment by vasani-arpit** [comment]
resolved in [0.27.0](https://github.com/vasani-arpit/WBOT/releases)
