### ISSUE TITLE
Dynamic Response via Eval / JSON

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [vasani-arpit/WBOT#30]
bot.json 

,
        {
            "contains": [],
            "exact": ["piada"],
            "response": "https://api.chucknorris.io/jokes/random",
	    "type":"json"
        },
        {
            "contains": [],
            "exact": ["date","time"],
            "response": "function evalTest() { var data = new Date();return data.toLocaleTimeString()+' '+data.toLocaleDateString(); }; evalTest();",
			"type":"eval"
        },

inject.js

				} else if(exactMatch.type == 'eval') {
					WAPI.sendMessage2(message.from._serialized, exactMatch.response);
				}

**Comment by andersondeoliveiramachado** [comment]
![image](https://user-images.githubusercontent.com/1152426/57731065-3a6ac000-7670-11e9-94e2-443a133f3a09.png)

**Comment by andersondeoliveiramachado** [comment]
SOLVED !

            page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36");
            page.setBypassCSP(true);

**Comment by andersondeoliveiramachado** [comment]
} else if(exactMatch.type == 'json') {
						fetch(exactMatch.response).then(response => response.json()).then(response => WAPI.sendMessage2(message.from._serialized, serialnumberTitle + response.value));

**Comment by vasani-arpit** [comment]
```js
page.setBypassCSP(true);
```
is enough. No need to change userAgent

**Comment by andersondeoliveiramachado** [comment]
I put the user agent as reference of where I placed the page.setBypassCSP(true);
