### ISSUE TITLE
Disable read receipts when noMatch is blank

### ISSUE THREAD

**Issue by vasani-arpit** [vasani-arpit/WBOT#303]
When noMatch is set to nothing. WBOT is still reads the message which is problematic. if noMatch set to nothing then WBOT should not read the messages so that user can read them later and reply accordingly.

**Comment by cromstudio21** [comment]
Como hago que el wbot no lea los mensajes?
para luego leerlos?

**Comment by vasani-arpit** [comment]
@cromstudio21 will provide an update for that.

**Comment by AngelJRomero21** [comment]
Se soluciono? Colocaran una solucion a este problema?

**Comment by vrushalipachchigar** [comment]
@AngelJRomero21 Yes we have found the issue and are working towards the solution. It will be provided in next release soon.

**Comment by vasani-arpit** [comment]
Should be fixed in v0.29.0
https://github.com/vasani-arpit/WBOT/releases

@vrushalipachchigar Please test this.

**Comment by vrushalipachchigar** [comment]
It's working properly @vasani-arpit
