### ISSUE TITLE
Temporary Bug Fix for checklogin function

### ISSUE THREAD

**Issue by tradename** [vasani-arpit/WBOT#306]
On the new whatsapp web version update you would see that if you close WBOT and try to run it again it would fail to work.

 you can change line 161 in **index.js**
 
_var output = await page.evaluate("localStorage['last-wid']");_
to 
 _var output = await page.evaluate("localStorage['last-wid-md']");_

They have changed that storage key

**Comment by vasani-arpit** [comment]
Should be fixed in v0.29.0
https://github.com/vasani-arpit/WBOT/releases

Please check and let me know. reopen if issue still persists.
