### ISSUE TITLE
The Bot is not working with latest Whatsapp Business Update

### ISSUE THREAD

**Issue by GonzaloAndrade** [vasani-arpit/WBOT#309]
When scanning the QR Code from a Whatsapp Business Device,  the first attempt works.
The second attempt shows the following:

![image](https://user-images.githubusercontent.com/1771862/152438758-4c57d590-6a29-4e3c-b2e5-5c35bdcaec90.png)

Normal Whatsapp seems to be fine.

**Comment by vasani-arpit** [comment]
Temporary solution to this has been mentioned in #306. 

for now you can try this solution https://github.com/vasani-arpit/WBOT/issues/298#issuecomment-1022028134

**Comment by vasani-arpit** [comment]
I have just tested WBOT in business multi-device with web version 2.2206.5. It works fine for me. You may run into the issue above after some time like 4-6 hours when whatsapp updates their tokens. at that time you can just logout and scan the QR again.

**Comment by vrushalipachchigar** [comment]
Closing this as detailed description provided in #321
