### ISSUE TITLE
Use wbot with emulator

### ISSUE THREAD

**Issue by kivervinicius** [vasani-arpit/WBOT#32]
I would not like to have to always keep a physical device connected 24h, would it be possible for me to scan the qrcode or pass the authorization code somehow to this emulator? Someone already did something like that.

**Comment by vasani-arpit** [comment]
Yes. It is possible. 

1. Create an emulator with play services in it.
2. Save an image of QR code from Whatsapp web
3. Set it as rear camera image in emulators camera options

Then you should be good to go. 🙂

**Comment by kivervinicius** [comment]
thank you, I will have to try, I just think there could be some way (some apk or something) that could via software send the qrcode to the application.

**Comment by vasani-arpit** [comment]
👍 Let me know how that goes.
