### ISSUE TITLE
WBOT doesn't work properly if multiple devices are logged in in whatsapp business 

### ISSUE THREAD

**Issue by vrushalipachchigar** [vasani-arpit/WBOT#321]
**Describe the bug**
When user has feature of multi device login on in WhatsApp, the bot doesn't recognize it even if user is logged in.

**To Reproduce**
1. Go to WhatsApp > Linked devices
2. Click on Multi device login
3. Add multiple devices
4. See error when you start the bot again

**Expected behavior**
If multi device is on, the bot should acknowledge that the user is logged in and start working accordingly.

**Screenshots**

![wbot-issue](https://user-images.githubusercontent.com/78303560/158586710-607d345d-cce4-4054-b777-0d5971ffb506.png)

**App information (please complete the following information):**
 - Version 2.2208.7
 - Windows 10
 - WhatsApp business

**Comment by vasani-arpit** [comment]
Should be fixed in v0.29.0
https://github.com/vasani-arpit/WBOT/releases

reopen if issue still persists.
