### ISSUE TITLE
Opcion de Ejecutar Wbot en HEROKU O DIGITALOCEAN

### ISSUE THREAD

**Issue by AngelJRomero21** [vasani-arpit/WBOT#323]
SERIA INTERESANTE QUE REALIZARA UN TUTORIAL DE COMO EJECUTAR WBOT EN HEROKU, ME GUSTARIA QUE FUERA EN HEROKU YA QUE SUS PLANES GRATIS SON MAS FLEXIBLES QUE DIGITALOCEAN

**Comment by vrushalipachchigar** [comment]
WBOT can't run on Heroku's free plan as it has some system requirements that aren't provided in free plan.
This feature is still in progress and we're working on it and trying to automate the process by just clicking on a button.
We would also provide documentation with details about same  for better understanding.

**Comment by AngelJRomero21** [comment]
Seria Excelente!
Una pregunta Como correr Wbot en Debian Server?

**Comment by vrushalipachchigar** [comment]
Debian is similar to Ubuntu so you can refer to the steps given on link https://github.com/vasani-arpit/WBOT#how-to-start-the-bot 
If you face any problem during installation, do let us know.
