### ISSUE TITLE
Media sending no longer working

### ISSUE THREAD

**Issue by deanylev** [vasani-arpit/WBOT#327]
**Describe the bug**
The `sendImage` function doesn't appear to be working anymore. When responding with a `files` array from my server, the images don't get sent anymore, and instead I get an error in my console (attached in the screenshots section).

**To Reproduce**
1. Call `WAPI.sendImage` with a base64 encoded image and chat ID.

**Expected behavior**
The image should be sent into the chat.

**Screenshots**
<img width="806" alt="image" src="https://user-images.githubusercontent.com/22049511/172998789-212f27e5-e5f9-4573-9b6f-174087afb456.png">

**App information (please complete the following information):**
 - Version: 0.28.0
 - OS: Debian 10

**Comment by vasani-arpit** [comment]
This is currently being fixed in #325

**Comment by Consir-Informatica** [comment]
Hi [deanylev](https://github.com/deanylev) .... find the WAPI.sendImage function and change ".models[0]" to "._models[0]" . For me it worked.

**Comment by deanylev** [comment]
@Consir-Informatica cheers, that's seems to have worked.

**Comment by StrikOne** [comment]
How do I reply to a message with more than one image? for example 2 images in 1 answer

**Comment by vasani-arpit** [comment]
If you are using webhook then it is just an array you can put as many message objects you like in the response.

**Comment by vasani-arpit** [comment]
Should be fixed in v0.29.0
https://github.com/vasani-arpit/WBOT/releases

Please check and let me know.
