### ISSUE TITLE
noMatch is showing up as an error

### ISSUE THREAD

**Issue by upal212** [vasani-arpit/WBOT#330]
**Describe the bug**
Bot is not reading the values of "noMatch":"{Example reply}" from the bot.json file and shows up as 'Message doesn't have media or it is not enabled in bot.config.json'

**To Reproduce**
1. Message any random letters not matching to any of your set replies
2. Click on 'Bot' cmd/terminal
3. See the error

**Expected behavior**
Should be reading the values of 'noMatch' from the bot.json file as per the previous version(s).

**Screenshots**
[https://imgur.com/a/3c18qnz](https://imgur.com/a/3c18qnz)

**App information (please complete the following information):**
 - Version: 0.29.0
 - OS: Windows Server 2019 x64

**Comment by vasani-arpit** [comment]
Thanks for reporting. Will check.

**Comment by vasani-arpit** [comment]
@upal212 #331 is merged. Please try v0.30.0
Reopen if issue persists.
