### ISSUE TITLE
How can I detect the messages that I send myself?

### ISSUE THREAD

**Issue by jasp402** [vasani-arpit/WBOT#332]
**Describe the solution you would like**
I would like to know how I can send and receive messages sent from my same number.

In the WAPI.js file, the variable **isSentByMe** and **isMe** were found. removed all validations on functions like **isChatMessage()** and **getAllMessageIdsInChat()**.

But I can't get it to work. Understanding that an indefinite loop can be generated. but I'm sure that can be handled.

any suggestion?

**Comment by vasani-arpit** [comment]
After Multi-device it is hard to get the messages from WA. You can keep track of what you sent. You can get chat items from `client`

https://github.com/vasani-arpit/WBOT/blob/master/src/index.js#L113

**Comment by jasp402** [comment]
Hi vasani! 

I have found that by changing this section I can already receive the messages I send. y It is possible to listen to my own messages if I am in a group.
The solution I used was to create a group for myself. It's not what I wanted but it works great for what I need.

![image](https://user-images.githubusercontent.com/8978470/183980029-ca0262b0-3e0e-45bb-8f26-aa0f665f244f.png)

**Comment by vasani-arpit** [comment]
Nice. Closing this as it is resolved now.
