### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by Ayman-Naim** [vasani-arpit/WBOT#333]
i face log in issue  in WBOT-0.28.0 
when scanning code it stuck with this message  "Waiting for scan Keep in mind that it will expire after few seconds User is not logged in. Waited"
![bot error](https://user-images.githubusercontent.com/52940205/187025785-3982704a-f884-4c22-b345-2de202246579.png)

what is the solution for this  issue

**Comment by vasani-arpit** [comment]
remove cache folders like chrome-* or session-data etc... and try again.

You can also copy the exe and json file to new location and execute from there.

**Comment by Ayman-Naim** [comment]
i deleted chromium-data and installed it again  and it still having the same error and tryied it from another location too

**Comment by Igor4Dantas** [comment]
I'm also facing the same problem.

But I noticed that whatsapp made an update in the system, where it inserted a "Business Guide" and from that moment, the bot stopped connecting the QrCode.

I tried to download all versions of wbot to test, got no result, also deleted chrome-* folder, cleared cache... and couldn't solve it yet.

Maybe you changed some of the source code of the Whatsapp Web page.

**Comment by Igor4Dantas** [comment]
> i deleted chromium-data and installed it again and it still having the same error and tryied it from another location too

Hello, I managed to solve the problem, using version 0.31.0.
When starting, the page will not be able to generate the QrCode, right click and reload the page, this will refresh and the QrCode will appear, scan and wBot will be able to identify that it hears the connection.

Sorry for the translator's english.

**Comment by Ayman-Naim** [comment]
> > i deleted chromium-data and installed it again and it still having the same error and tryied it from another location too
> 
> Hello, I managed to solve the problem, using version 0.31.0. When starting, the page will not be able to generate the QrCode, right click and reload the page, this will refresh and the QrCode will appear, scan and wBot will be able to identify that it hears the connection.
> 
> Sorry for the translator's english.

but the new version is not supporting  'setupSmartReply' old function  so my added code is not working because of it

**Comment by Ayman-Naim** [comment]
> New version released v0.32.0 Try it out. https://github.com/vasani-arpit/WBOT/releases



the new version is not solving this problem 

try this and it will work  >>return await page.waitForSelector('[class="_26aja _1dEQH"]')
