### ISSUE TITLE
Cannot read properties of undefined (reading 'LegacyPhoneFeatures')

### ISSUE THREAD

**Issue by chalfling** [vasani-arpit/WBOT#341]
Hello!

Error when trying to run wbot-linux. I think this is able to fix:
https://github.com/pedroslopez/whatsapp-web.js/issues/1913

Thank you!

**Comment by vasani-arpit** [comment]
Thanks for reporting. 

Looks like solution is not merged in their main branch. I'll add a patch into my repo.
