### ISSUE TITLE
Project is not working

### ISSUE THREAD

**Issue by JRakhimov** [vasani-arpit/WBOT#35]
Seems like Web Whatsapp changes webpack version or webpack itself

**Comment by derodevil** [comment]
I cannot send message. It gives me `chat.sendMessage is not a function`

**Comment by dennyphilipp** [comment]
yes, I'm also having the same problem, the function no longer exists, has anyone found a solution?

**Comment by NelsonGaldeman** [comment]
Try printing out "chatSend" var and see its methods. Just before this [line](https://github.com/vasani-arpit/WBOT/blob/master/src/WAPI.js#L333)

**Comment by NelsonGaldeman** [comment]
> 
> 
> I cannot send message. It gives me `chat.sendMessage is not a function`

Which script/line? Try to print out "chat" variable and see what's happening.

**Comment by derodevil** [comment]
> > I cannot send message. It gives me `chat.sendMessage is not a function`
> 
> Which script/line? Try to print out "chat" variable and see what's happening.

Line 697 `window.WAPI.sendMessageToID`. It seems this function `chat.sendMessage` (line 703) no longer exists

**Comment by NelsonGaldeman** [comment]
I would add `console.log(chat)` before `chat.sendMessage` (both lines 703 & 708). Maybe it's not the function (since it's defined) but the object itself.

**Comment by dennyphilipp** [comment]
Geez, I got it.
!function () { const o = function (e) { o.mID = Math.random().toString(36).substring(7); o.mObj = {}; o.cArr = []; o.mGet = null; e ? o.debug = !0 : window.mRdebug ? o.debug = !0 : o.debug = !1; o.log = function (e) { o.debug && console.warn(`[moduleRaid] ${e}`) }; o.args = [[[0], [function (e, n, t) { mCac = t.c; Object.keys(mCac).forEach(function (e) { o.mObj[e] = mCac[e].exports }); o.cArr = t.m; o.mGet = t }]], [[1e3], { [o.mID]: function (e, n, t) { mCac = t.c; Object.keys(mCac).forEach(function (e) { o.mObj[e] = mCac[e].exports }); o.cArr = t.m; o.mGet = t } }, [[o.mID]]]]; fillModuleArray = function () { if ("function" == typeof webpackJsonp) o.args.forEach(function (e, n) { try { webpackJsonp(...e) } catch (e) { o.log(`moduleRaid.args[${n}] failed: ${e}`) } }); else try { webpackJsonp.push(o.args[1]) } catch (e) { o.log(`Pushing moduleRaid.args[1] into webpackJsonp failed: ${e}`) } if (0 == o.mObj.length) { mEnd = !1; mIter = 0; if (!webpackJsonp([], [], [mIter])) throw Error("Unknown Webpack structure"); for (; !mEnd;)try { o.mObj[mIter] = webpackJsonp([], [], [mIter]); mIter++ } catch (o) { mEnd = !0 } } }; fillModuleArray(); get = function (e) { return o.mObj[e] }; findModule = function (e) { results = []; modules = Object.keys(o.mObj); modules.forEach(function (n) { mod = o.mObj[n]; if ("undefined" != typeof mod) { if ("object" == typeof mod.default) for (key in mod.default) key == e && results.push(mod); for (key in mod) key == e && results.push(mod) } }); return results }; findFunction = function (e) { if (0 == o.cArr.length) throw Error("No module constructors to search through!"); results = []; if ("string" == typeof e) o.cArr.forEach(function (n, t) { n.toString().includes(e) && results.push(o.mObj[t]) }); else { if ("function" != typeof e) throw new TypeError("findFunction can only find via string and function, " + typeof e + " was passed"); modules = Object.keys(o.mObj); modules.forEach(function (n, t) { mod = o.mObj[n]; e(mod) && results.push(o.mObj[t]) }) } return results }; return { modules: o.mObj, constructors: o.cArr, findModule: findModule, findFunction: findFunction, get: o.mGet ? o.mGet : get } }; "object" == typeof module && module.exports ? module.exports = o : window.mR = o(); window.Store = window.mR.findModule("Conn")[0].default }();

var Stored = window.Store;
Stored.SendMessage = window.mR.findModule("sendTextMsgToChat")[0].sendTextMsgToChat;
var chat = Store.Chat.models.filter(x => x.id.user === "XXXXXXX")[0];
Store.SendMessage(chat, "Hello World");

**Comment by derodevil** [comment]
> Geez, I got it.
> !function () { const o = function (e) { o.mID = Math.random().toString(36).substring(7); o.mObj = {}; o.cArr = []; o.mGet = null; e ? o.debug = !0 : window.mRdebug ? o.debug = !0 : o.debug = !1; o.log = function (e) { o.debug && console.warn(`[moduleRaid] ${e}`) }; o.args = [[[0], [function (e, n, t) { mCac = t.c; Object.keys(mCac).forEach(function (e) { o.mObj[e] = mCac[e].exports }); o.cArr = t.m; o.mGet = t }]], [[1e3], { [o.mID]: function (e, n, t) { mCac = t.c; Object.keys(mCac).forEach(function (e) { o.mObj[e] = mCac[e].exports }); o.cArr = t.m; o.mGet = t } }, [[o.mID]]]]; fillModuleArray = function () { if ("function" == typeof webpackJsonp) o.args.forEach(function (e, n) { try { webpackJsonp(...e) } catch (e) { o.log(`moduleRaid.args[${n}] failed: ${e}`) } }); else try { webpackJsonp.push(o.args[1]) } catch (e) { o.log(`Pushing moduleRaid.args[1] into webpackJsonp failed: ${e}`) } if (0 == o.mObj.length) { mEnd = !1; mIter = 0; if (!webpackJsonp([], [], [mIter])) throw Error("Unknown Webpack structure"); for (; !mEnd;)try { o.mObj[mIter] = webpackJsonp([], [], [mIter]); mIter++ } catch (o) { mEnd = !0 } } }; fillModuleArray(); get = function (e) { return o.mObj[e] }; findModule = function (e) { results = []; modules = Object.keys(o.mObj); modules.forEach(function (n) { mod = o.mObj[n]; if ("undefined" != typeof mod) { if ("object" == typeof mod.default) for (key in mod.default) key == e && results.push(mod); for (key in mod) key == e && results.push(mod) } }); return results }; findFunction = function (e) { if (0 == o.cArr.length) throw Error("No module constructors to search through!"); results = []; if ("string" == typeof e) o.cArr.forEach(function (n, t) { n.toString().includes(e) && results.push(o.mObj[t]) }); else { if ("function" != typeof e) throw new TypeError("findFunction can only find via string and function, " + typeof e + " was passed"); modules = Object.keys(o.mObj); modules.forEach(function (n, t) { mod = o.mObj[n]; e(mod) && results.push(o.mObj[t]) }) } return results }; return { modules: o.mObj, constructors: o.cArr, findModule: findModule, findFunction: findFunction, get: o.mGet ? o.mGet : get } }; "object" == typeof module && module.exports ? module.exports = o : window.mR = o(); window.Store = window.mR.findModule("Conn")[0].default }();
> 
> window.Store.SendMessage = window.mR.findModule("sendTextMsgToChat")[0].sendTextMsgToChat;
> var chat = Store.Chat.models.filter(x => x.id.user === "XXXXXXX")[0];
> Store.SendMessage(chat, "Hello World");

Thanks. The last 3 line works for me

**Comment by vasani-arpit** [comment]
Project works completely fine. Checked with Version 0.3.2846 of whatsapp web.

**Comment by vasani-arpit** [comment]
I am updating the WAPI.js check development branch for latest update.
