### ISSUE TITLE
Wbot : after Launching browser 

### ISSUE THREAD

**Issue by muhammaddanish321** [vasani-arpit/WBOT#355]
I currently have a problem when I scan the QrCode but system waiting Launching browser !
it not move next step ( AUTHENTICATED ).

[Release v0.43.0]

![whatsapp error](https://github.com/vasani-arpit/WBOT/assets/107614017/b869e6c2-a9be-4502-b1fc-8e3ee0dbf4e4)

**Comment by vasani-arpit** [comment]
new version released. Please test it out.

**Comment by upal212** [comment]
> new version released. Please test it out.

Same problem with the latest version 0.44.0
Please check the issue

**Comment by vasani-arpit** [comment]
Resolved in version 0.49

Please try it out.

**Comment by upal212** [comment]
> Resolved in version 0.49
> 
> Please try it out.

Still the same result with 0.49

**Comment by upal212** [comment]
> Resolved in version 0.49
> 
> Please try it out.

Working perfectly now!
Thank you so much for the quick fix.
