### ISSUE TITLE
Uncaught ReferenceError: webpackChunkwhatsapp_web_client is not defined

### ISSUE THREAD

**Issue by mohdsaeed7849** [vasani-arpit/WBOT#363]
I don't know, my whatsapp version is changed from 2.2412.50 to 2.3000.1012373576

that is giving me error in wapi.js: 
webpackChunkwhatsapp_web_client is not defined.

**Comment by vasani-arpit** [comment]
Whatsapp has moved away from webpack to their internal build system called comet. There are several solutions mentioned in this issue. https://github.com/pedroslopez/whatsapp-web.js/issues/2789 please try them out.

**Comment by mbnaj** [comment]
what is the solution?

**Comment by vasani-arpit** [comment]
either https://github.com/pedroslopez/whatsapp-web.js/issues/2789#issuecomment-2018399590 or https://github.com/pedroslopez/whatsapp-web.js/issues/2789#issuecomment-1992260938 should work. IMO. You can do both.

**Comment by mohdsaeed7849** [comment]
@vasani-arpit clearing the cookies logs me out of whatsapp

**Comment by mohdsaeed7849** [comment]
you can find the updated wapi.js that is compatible in  both 2.2X and 2.3X , [](https://github.com/mikelustosa/Projeto-TInject/blob/master/Source/JS/js.abr)

**Comment by kivlanzein** [comment]
@mohdsaeed7849 please help me to fix this problem, I got the same problem webpackChunkwhatsapp_web_client is not defined? there is a solution

does this code work for you?
https://github.com/mikelustosa/Projeto-TInject/blob/master/Source/JS/js.abr

**Comment by mohdsaeed7849** [comment]
@kivlanzein yes, it worked for me.

**Comment by kivlanzein** [comment]
@mohdsaeed7849 okay thanks, worked for me to

**Comment by kivlanzein** [comment]
@mohdsaeed7849 can you help me how to send a message to a new number? I use this

WAPI.sendMessage2() .. works if you have already chatted with a bot, cannot send messages if you have never chatted with a bot (new number)

**Comment by vasani-arpit** [comment]
Temporary fix has been added in latest version https://github.com/vasani-arpit/WBOT/releases
