### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by shajji1** [vasani-arpit/WBOT#39]
Can we add custom properties e.g _ID_ when sending message/file to user, so when we get readreciept we can recognize that message.

**Comment by vasani-arpit** [comment]
Yes. You will receive ID and other properties for each incoming/outgoing message. check inject.js for more exact info on this. 

What exactly your use case here?

**Comment by shajji1** [comment]
My use case is, when i sent message to user by `Store.Chat.get('XXXXX').sendMessage('hello');` i want to add  some custom properties e.g `CustomID`. so when i get readreciept of this message i can identify by CustomId property what message is this.

Thanks for prompt response :)

**Comment by vasani-arpit** [comment]
You don't need to each message already has an ID property using which you can query the `ack` property. 
here is a value break-down of `ack` property 

0 - Message is not sent 
1 - Message sent but not received
2 - Message sent and received

**Comment by shajji1** [comment]
Yes, you are correct there is ID property. Thanks
