### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by bsenyuva** [vasani-arpit/WBOT#4]
**Describe the bug**
There is a browser version error occurring when you start the wbot-win.exe with existing session.

**To Reproduce**
1. Run wbot-win.exe, wait installations and login to WhatsApp via QR code
2. Close the CLI using Ctrl+C or close button
3. Re-run wbot-win.exe

**Expected behavior**
App should behave already logged in and start the bot server flawlessly.

**Screenshots**
![error](https://user-images.githubusercontent.com/3096523/54994823-41614480-4fd6-11e9-9dd6-34c83ae890dd.png)

![cli](https://user-images.githubusercontent.com/3096523/54994844-5211ba80-4fd6-11e9-94d9-45e6fdb63162.gif)

**App information (please complete the following information):**
 - Version: 0.3 Beta
 - OS: Win 10 Pro

**Additional context**
It runs without problem if you delete ChromeSession folder, run wbot-win.exe and login to WhatsApp via QR code again.

**Comment by vasani-arpit** [comment]
Thanks for raising the issue. Will look into it.

**Comment by vasani-arpit** [comment]
Issue has been fixed in development branch. Will be released in next update with dark-theme, group-flag.. etc... features.

**Comment by vasani-arpit** [comment]
Resolved in version 0.4
