### ISSUE TITLE
Can't run on Ubuntu 16.04

### ISSUE THREAD

**Issue by AndikaTanpaH** [vasani-arpit/WBOT#41]
> ~/wbot-linux-0.8$ chmod +x ./wbot-linux
> ~/wbot-linux-0.8$ ./wbot-linux
> bash: ./wbot-linux: cannot execute binary file: Exec format error

After i extract and change permission i got this.

**Comment by vasani-arpit** [comment]
As per my understanding you need to have either gnome or KDE environment to run this. This will not work on VPS or in headless mode.

**Comment by vasani-arpit** [comment]
Feel free to reopen If you facing issues.

**Comment by AndikaTanpaH** [comment]
hi, I think i found the problem..
this precompile is not work on ubuntu 32bit machine, I dont have 64bit version.

and if I run manually from source npm/node, 
look on linux `https://omahaproxy.appspot.com/all.json?os=linux` not available for `canary channel`
