### ISSUE TITLE
Parse Object Message for save in local database

### ISSUE THREAD

**Issue by mrfwn** [vasani-arpit/WBOT#44]
Is it possible to parse the message object to save to a local database? I am being barred by the CSP. I tried inserting meta tag to release, but it didn't work. Would you help me ?

**Comment by mrfwn** [comment]
![erro_csp](https://user-images.githubusercontent.com/13460706/61926959-35b46900-af49-11e9-8159-cb825fe2b2ae.JPG)

var meta = document.createElement('meta');
meta.httpEquiv = "Content-Security-Policy";
meta.content = "default-src 'self' gap:; script-src 'self' data: * 'unsafe-eval'; object-src *; style-src 'self' data: 'unsafe-inline'; img-src * 'self' data: http:; media-src 'self' data:; font-src 'self' data:; connect-src *";
var tag = document.getElementsByTagName('head')[0]
tag.insertBefore(meta,tag.childNodes[0])

parser:

window.WAPI.saveMsgdb = function (message){
    var url = "http://localhost/message";
    var json = JSON.stringify(message);
    var xhr = new XMLHttpRequest();    
    xhr.open("POST", url, true);
    xhr.setRequestHeader('Content-type','application/json; charset=utf-8');
    xhr.onload = function () {
        var users = JSON.parse(xhr.responseText);
        window.log(users)
        
        if (xhr.readyState == 4 && xhr.status == "201") {
            console.table(users);
        } else {
            console.error(users);
        }
    }
    xhr.send(json);
}

**Comment by vasani-arpit** [comment]
Congratulations !! On opening your first issue.

You can bypass the CSP using the puppeteer's setBypassCSP method

```js
page.setBypassCSP(enabled);
```

[know more from here](https://pptr.dev/#?product=Puppeteer&version=v1.18.1&show=api-pagesetbypasscspenabled)

**Comment by vasani-arpit** [comment]
Use webhooks it is available in latest build.
