### ISSUE TITLE
Message Forwarding

### ISSUE THREAD

**Issue by tradename** [vasani-arpit/WBOT#45]
How can I forward (POST) the message  to a PHP file in a remote URL after meeting certain conditions in the Bot.json file.

**Comment by joska1993** [comment]
i need to do this

**Comment by vasani-arpit** [comment]
It is being developed at [webhooks](https://github.com/vasani-arpit/WBOT/tree/features/webhooks) branch. code is complete documentation is in progress.

**Comment by lucas-engen** [comment]
@vasani-arpit this feature has been implemented, right?

**Comment by vasani-arpit** [comment]
> @vasani-arpit this feature has been implemented, right?

Yes. Webhooks are implemented and working properly. Just configure your URL in not.json and start receiving request for each messages. Make sure you have cors enabled in the server.

**Comment by vasani-arpit** [comment]
Closing for now. Reopen if needed.
