### ISSUE TITLE
Sending location

### ISSUE THREAD

**Issue by giladno** [vasani-arpit/WBOT#46]
Any idea how to send a location (lat/lng)? I can parse incoming location messages, but not sure how to send one.

**Comment by vasani-arpit** [comment]
Haven't checked about that. Look into WAPI.js. maybe there is a function for that.

**Comment by giladno** [comment]
I did, couldn't find any :(

**Comment by jrrcdev** [comment]
You can't send location in whatsapp web, here is the same.

**Comment by vasani-arpit** [comment]
I suggest you to use Google maps link for ease of use and ease of development.

If you still want to do it then check [this](https://github.com/alfred82santa/whalesong). docs says it has live location but I haven't tested it. In fact, I was unable to setup this project on my machine.
