### ISSUE TITLE
Cant run

### ISSUE THREAD

**Issue by beecoder77** [vasani-arpit/WBOT#5]
How to run on linux? when i run wbot-linux, always got result 

> wbot-linux: command not found

**Comment by vasani-arpit** [comment]
make sure you are at the diractory where wbot-linux file is located. do a `ls` or `ll` to see whether file is there or not.

**Comment by vasani-arpit** [comment]
you need to do 
```sh
chmod +x wbot-linux
```

first to make it executable then just
```
wbot-linux
```
