### ISSUE TITLE
Reply messages

### ISSUE THREAD

**Issue by Gabslocked** [vasani-arpit/WBOT#50]
![image](https://user-images.githubusercontent.com/37151013/63172459-1f636f80-c014-11e9-9bc7-a71170d68431.png)

Do you know any way to reply to messages this way?

I've tried it in several ways by injecting quoted objects into the message, like:

`  chat.sendMessage(message, {
				linkPreview : null,
				mentionedJidList : null,
				quotedMsg : {
          "type": "chat",
          "body": messageObject.body
        },`

**Comment by vasani-arpit** [comment]
Haven't tried that. will check and let you know.

**Comment by Gabslocked** [comment]
Good morning, some news?

**Comment by andersondeoliveiramachado** [comment]
https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/594

**Comment by andersondeoliveiramachado** [comment]
Fix Reply With Quote
@vasani-arpit 
https://github.com/mukulhase/WebWhatsapp-Wrapper/pull/793

**Comment by vasani-arpit** [comment]
@andersondeoliveiramachado thanks. will add

**Comment by cobadulu001** [comment]
is this already implemented ?
it seems still not quoted the message
