### ISSUE TITLE
Bug - Search keywords with url

### ISSUE THREAD

**Issue by hocxpol** [vasani-arpit/WBOT#51]
var url = "https://my-json-server.typicode.com/typicode/demo/posts";
var webMessage = "";
var request = require("request");
request({
    url: url,
    json: true
}, function (error, responsex, body) {
    if (!error && responsex.statusCode === 200) {
        var webMessage = body;
        //console.log(body);
    }
});

 //var webMessage is empty, help me pleas
response = webMessage;
console.log(`Replying with ` + response);

**Comment by vasani-arpit** [comment]
Please explain what you are trying to achieve. and what seems to be a bug?

**Comment by hocxpol** [comment]
I need to bring the json result from a url, but when I try to pass the result "body" to var webMessage it doesn't get

**Comment by vasani-arpit** [comment]
I suggest you to have a look at this branch 
https://github.com/vasani-arpit/WBOT/tree/features/webhooks

It not done yet. but it will be helpful.
