### ISSUE TITLE
Initiate new chat messages to new numbers

### ISSUE THREAD

**Issue by alijundi** [vasani-arpit/WBOT#54]
I am hoping there is a way to initiate the chat instead of just responding message. If there is, what is the function to be used in WAPI.js? I really need to initiate the conversation and then respond to messages as it comes.

**Comment by alijundi** [comment]
Hi @vasani-aprit

Do you think it can be done? I have researching this issue since last night. I appreciate your insight.

**Comment by vasani-arpit** [comment]
You can do that but that's against Whatsapp's policy. I don't recommend that. If you still want to do it then you can the same function which is being used to send messages.

You can write it outside of message receive event.
