### ISSUE TITLE
Fake Json-server example

### ISSUE THREAD

**Issue by magadan** [vasani-arpit/WBOT#60]
Hello ! PLs, can you create a simple fake-json server example to work with WBOT ?

https://github.com/typicode/json-server

Thank you !

**Comment by vasani-arpit** [comment]
Have you tried as per https://github.com/vasani-arpit/WBOT/blob/master/docs/Webhook-example.md ?

**Comment by magadan** [comment]
Yes, but no success... Im newbie with node. I think fake-json is very easy to start.

A tip: did you check [n8n.io](url), i think is very nice to create nice integrations with WBOT.

Thanks for the app, its work very good and very simple !

**Comment by vasani-arpit** [comment]
n8n looks nice. I am also making something like that https://github.com/vasani-arpit/Social-Media-Automation

Will improve documentation for wbot webhook this weekend.

**Comment by magadan** [comment]
Thank you !

**Comment by UFO-84** [comment]
You can use this Chat Bot API service. Please look down bottom of the page. No real life usage but works for demo. Returns as JSON.

https://www.drivebird.com/services/anonymous-chat

Just edit the WBOT js file for result text message.
