### ISSUE TITLE
Not all messages are being sent to Webhook

### ISSUE THREAD

**Issue by GonzaloAndrade** [vasani-arpit/WBOT#61]
Hi, I was stress testing the webhook feature and I found that if I send a few messages in a short period of time, lets say 5 per second, just 1 or 2 are only sent to the hook, the other 3 messages are ignored. Do you have any workaround in mind?
Thanks!

**Comment by vasani-arpit** [comment]
How about the rest of the code execution. It did not called webhook for those three but did it called rest of the code after that? like replying and such?

**Comment by panteLx** [comment]
btw same for me bot isnt even checking the other messages just one every 2 secs i guess
