### ISSUE TITLE
Dialogflow integration

### ISSUE THREAD

**Issue by harsh4870** [vasani-arpit/WBOT#66]
First It's amazing code to work on Thanks a lot for sharing the code.

I have integrated Dialogflow with this WBOT, if the response is not available in `bot.json` it's fallback on my Dialogflow intents. 
 
Is there any way can you suggest if we can do human handover mechanism here. If use online from any other device we can break functionality. 

Is there any possibility or variable where we are getting state of the user or device activity.

**Comment by vasani-arpit** [comment]
Can you explain more on your stack?  If I understood this correctly I think you will need a middleware service to pass messages between these two nodes and provide a room for human intervention.

**Comment by harsh4870** [comment]
Yes i have integrated Dialogflow with your code. First, check for a message in `bot.json` if no match it's go to  Dialogflow and check for intent. I have trained model on Dialogflow. 

So i am looking forward to adding human integration.  When user is available and typing BOT does not have to reply.

**Comment by vasani-arpit** [comment]
Cool. Can you commit DialogFlow integration and make an PR? I am working on a human integration as a fallback of Botkit Integration I created.

**Comment by harsh4870** [comment]
Sure i will commit and make an PR.
