### ISSUE TITLE
How to work webhooks?

### ISSUE THREAD

**Issue by FitterX** [vasani-arpit/WBOT#69]
Hi all.
I try webhooks but no have success.

Have tutorial?

**Comment by vasani-arpit** [comment]
You can take a look at https://github.com/vasani-arpit/WBOT/blob/master/docs/Webhook-example.md for now. I am planing to write a article or make a video about that.

**Comment by FitterX** [comment]
Hey Vasani, thank you!

I'm using php to get the message and the type is working!
But I can't send the return (response) through PHP.
Can you help me with a little example?

**Comment by vasani-arpit** [comment]
here is what your php endpoint should return

```
[{
      "text": "Look, Reply from Webhook!",
      "type": "message"
}]
```

You can check the errors by opening DevTools of the whatsapp window.

**Comment by FitterX** [comment]
i try this!
echo json_encode(['"text"' => 'test', '"type"' => 'message']);

result:
{
"text": "test",
"type": "message"
}

**Comment by FitterX** [comment]
Hey..sorry..
I add brackets its work now! 
Thank for help!

**Comment by setijo** [comment]
I thank you, the application is running well.
I have been able to create a BOT using the webhook.
I would like his help to provide examples of utilizing existing functions, such as:
1. Send image files
2. Get whatsapp id / number

window.WAPI.getMyContacts = function () {
    return window.Store.Contact.filter((contact) => contact.isMyContact === true).map((contact) => WAPI._serializeContactObj(contact));
};

BR
