### ISSUE TITLE
Webhook response with image

### ISSUE THREAD

**Issue by FitterX** [vasani-arpit/WBOT#70]
Hello!
How do I send an image as a response on webhook?

I converted an image to base64 and made the array according to your example, but didn't get the image.

What is missing to work?

[
{
text: "teste",
type: "message",
files: [
{
name: "1.jpeg",
file: ""data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQ.....................no write all text"
}
]
}
]

**Comment by oOHiyoriOo** [comment]
maybe cuz u open the base 64 string with 2x " 
```
there
||
\/
""data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQ.....................no write all text"
```
