### ISSUE TITLE
Message sending broke down

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [vasani-arpit/WBOT#71]
Patch for Fix 

https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/754

**Comment by vasani-arpit** [comment]
Thanks for pointing that out. Add a fix in master.

**Comment by vasani-arpit** [comment]
New version 0.11 has been released which has this fix. 

https://github.com/vasani-arpit/WBOT/releases

Thanks again for reporting this.
