### ISSUE TITLE
Can i send audio files // mp3 files in base64 format too? 

### ISSUE THREAD

**Issue by oOHiyoriOo** [vasani-arpit/WBOT#78]
i tryed to make a bot which u can send youtube url's and it sends back the mp3 file.
sadly i cant get it to send the file :/ so i wondered if it is even possible bacuse in the source code it only has and "sendImage" function.

**Comment by vasani-arpit** [comment]
Although, the name of the function is `sendImage` you can send anything. from pdf to video. the condition is it has to be base64 that's it.

**Comment by oOHiyoriOo** [comment]
how do i have to format it currently iam sending:
```json
[{
    "text":"Here's your text",
    "type":"message",
    "files":[
        "name":"test.mp3",
        "file":"<plain base 64 string (like: 'SUQzBAAAAAAAI1RT...')>"
    ]
}]
```

**Comment by oOHiyoriOo** [comment]
btw i use webhook to handle the msg's
