### ISSUE TITLE
Dynamic Response? 

### ISSUE THREAD

**Issue by m7mdcc** [vasani-arpit/WBOT#8]
Hello 
Can we add some webhook or API to handle message reply ? 

Thanks

**Comment by vasani-arpit** [comment]
Yes. This feature is in pipeline. Feature branch has been created.

**Comment by jessicastorm1986** [comment]
Are you planning to manage dynamic messages with php,mysql ? this will become useable, static messages are not helping much to use your library. By when shall we expect this update ?

and how do we format ?

`            "contains": ["address"],
            "exact": ["address"],
            "response": "Address: 65 Ludlow St, New York, NY 10002, USA"
        },`

I want "New York" to come in 2nd line and "USA" to come in 3rd line.

**Comment by vasani-arpit** [comment]
@jessicastorm1986 
Webhooks are in pipeline down the road after 2-3 weeks once I am done with smart-reply feature/branch. 

for your second issue I suggest you should create a new issues as it is not related to Webhooks or dynamic reply topic.

**Comment by jfkz** [comment]
@vasani-arpit 
I need this feature and start working on it. If it may help - i will send request for review when finish.

**Comment by vasani-arpit** [comment]
Thanks. @jfkz 
I'll review your PR. 👍

**Comment by vasani-arpit** [comment]
Closing as webhook has been added in latest build.
