### ISSUE TITLE
Request to another site inside browser

### ISSUE THREAD

**Issue by LeoFC97** [vasani-arpit/WBOT#80]
I want to perform a api get when i recive some especific mensage and return the response via whatsapp, but i got fucked by cors, is there any way i can do this?

`                    var xhr = new XMLHttpRequest();
                    xhr.open('GET', 'https://www.google.com/');
                    xhr.send(null);`
Access to XMLHttpRequest at 'https://www.google.com/' from origin 'https://web.whatsapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by vasani-arpit** [comment]
If you look at [inject.js](https://github.com/vasani-arpit/WBOT/blob/master/src/inject.js#L10) it is already doing that with the webhook url using [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Examples)

Cors is enabled for the puppeteer tab so there should not be any error related to cors. Please pull master if you haven't.

**Comment by LeoFC97** [comment]
How do I resolve this?

![image](https://user-images.githubusercontent.com/33994116/71419602-049ea880-264f-11ea-9797-493f71ada4ea.png)

**Comment by vasani-arpit** [comment]
@LeoFC97 
Change the URL in bot.json to where your message receiving server is running.

**Comment by LeoFC97** [comment]
Oh the appconfig.webhook? I'am noob with node, sorry but i dont know where my server is running

**Comment by LeoFC97** [comment]
> @LeoFC97
> Change the URL in bot.json to where your message receiving server is running.

Im using the same server as you, the standard one
