### ISSUE TITLE
Can someone teach me how to send files using Webhook Response

### ISSUE THREAD

**Issue by oOHiyoriOo** [vasani-arpit/WBOT#81]
Hey i made an webhook server for WBOT and its working fine.
but now i want to send images and other files but everytime i respode with base64 file i dont get anything..

example response i send: 
`
 [
    {
        "text":"iam mister meesiks look at me!",
        "type":"message",
        "files":[
            {
                "name":"test.jpg",
                "file":"data:image/jpeg;base64"+<base64 of img>
            }
        ] 
    }
]
`

**Comment by vasani-arpit** [comment]
Looks like so many people having trouble with this. I will make a video for this so that it can be understood easily.

**Comment by oOHiyoriOo** [comment]
thy for that.

iam sry, iam sure it isn't that hard but
i tryed so many other ways to get it to work and i didn't got it.

**Comment by oOHiyoriOo** [comment]
Sry to disturb u but how fare are u with the video ? 
Iam really interested in sending files :3

**Comment by vasani-arpit** [comment]
@oOHiyoriOo was planning to do that last weekend but couldn't. will do this week.

**Comment by Hexenon** [comment]
@vasani-arpit @oOHiyoriOo  there is an error about this in the application, ill send a PR with the fixes.

**Comment by oOHiyoriOo** [comment]
@Hexenon should sending files now work? 
just asking to know if i can test again if ill get it to work on my own.

**Comment by Hexenon** [comment]
@oOHiyoriOo  i did this PR https://github.com/vasani-arpit/WBOT/pull/92
you can download those changes and respond to the webhook the following structure: 

```js
  {
    "text": "Look, quick replies!",
    "type": "message",
    "files":[{
        "name":"Name of the file",
        "file":"<Base64-string-of-the-file>"
    }]
  }
```
