### ISSUE TITLE
Import libs

### ISSUE THREAD

**Issue by LeoFC97** [vasani-arpit/WBOT#82]
I want to use firebase with this awesome bot, but i need to import the libs. 

i need to import the cdn like this:   <script src="https://www.gstatic.com/firebasejs/6.2.0/firebase-firestore.js"></script>

Where is the right place to do this?

**Comment by vasani-arpit** [comment]
You can use puppeteer's addScriptTab method to add [javaScripts](https://pptr.dev/#?product=Puppeteer&version=v2.0.0&show=api-pageaddscripttagoptions) to the page.

You can write as many script as you want in index.js in `injectScripts` function after line [144](https://github.com/vasani-arpit/WBOT/blob/master/src/index.js#L114)

```
    await page.addScriptTag({ url: "https://www.gstatic.com/firebasejs/6.2.0/firebase-firestore.js" });
```

**Comment by vasani-arpit** [comment]
Closing for now. Reopen if needed.
