### ISSUE TITLE
How did you build the app to have linux version?

### ISSUE THREAD

**Issue by mrbarnk** [vasani-arpit/WBOT#83]
Hello, I want to compile my app.

I don't want anybody to steal my code.

How can I do it like yours?

**Comment by vasani-arpit** [comment]
If you have node and packages installed for the project then you can run ```npm run pack``` it will make packages for all three OS.

**Comment by pavanmehta91** [comment]
use npm module `pkg` @mrbarnk

**Comment by mrbarnk** [comment]
It's not working , it's saying no node staisfy for node13

**Comment by pavanmehta91** [comment]
can you share the github link to your repo or something.

**Comment by mrbarnk** [comment]
Here is my json file

```{
  "name": "js",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "bin": "bin.js",
  "dependencies": {
    "axios": "^0.19.0",
    "compression": "^1.7.4",
    "express": "^4.17.1",
    "express-status-monitor": "^1.2.7",
    "fs-extra": "^8.1.0",
    "helmet": "^3.21.2",
    "node-cron": "^2.0.3",
    "rimraf": "^3.0.0",
    "sqlite3": "^4.1.1",
    "sulla-hotfix": "^1.2.12",
    "validate-phone-number-node-js": "^0.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.7.4",
    "@babel/preset-env": "^7.7.4",
    "babel-loader": "^8.0.6",
    "connect-flash": "^0.1.1",
    "express": "^4.16.4",
    "express-fileupload": "^1.1.1-alpha.1",
    "express-handlebars": "^3.0.0",
    "express-session": "^1.15.6",
    "flash": "^1.1.0",
    "gulp": "^4.0.2",
    "method-override": "^3.0.0",
    "mongoose": "^5.4.2",
    "nexe": "^3.3.2",
    "pack": "^2.2.0",
    "web": "0.0.2",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10",
    "webpack-node-externals": "^1.7.2"
  },
  "scripts": {
    "start": "node bin.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "nexe"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "pkg": {
    "scripts": "build/**/*.js",
    "assets": "views/**/*"
  },
  "bin": "index.js"
}```



I install pkg globbaly

and when I run `pkg .`

it brings out this error

`> pkg@4.4.2
> Targets not specified. Assuming:
  node13-linux-x64, node13-macos-x64, node13-win-x64
> Error! No available node version satisfies 'node13'`

**Comment by vasani-arpit** [comment]
This `package.json` is from other project. have you run `npm run pack` where wbot is? If you have then please share the output.

**Comment by mrbarnk** [comment]
What I got after copying somethings in this package.json file to my own project,
`> js@1.0.0 pack /home/mrbarnk/Documents/projects/nodejs/whatsapp_api
> pkg .

> pkg@4.4.2
> Error! No available node version satisfies 'node13'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! js@1.0.0 pack: `pkg .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the js@1.0.0 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mrbarnk/.npm/_logs/2020-01-04T10_43_28_294Z-debug.log`

**Comment by vasani-arpit** [comment]
PKG is not supported for the node version you have in your system. Please install node version 10.15+ then try to run `pkg .`

**Comment by mrbarnk** [comment]
Thanks so much.

I tried that, it worked fine until it got to linux and it said 

`Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  node_modules/puppeteer/.local-chromium
  path-to-executable/puppeteer`

**Comment by vasani-arpit** [comment]
That is just a warning. check the files. you will have your binary in current folder.

**Comment by mrbarnk** [comment]
ok...

Thanks very much.
All done.

**Comment by mrbarnk** [comment]
I got this after running it.

`Error: File '/**/whatsapp_api/node_modules/express-status-monitor/src/public/stylesheets/default.css' was not included into executable at compilation stage. Please recompile adding it as asset or script.`

**Comment by vasani-arpit** [comment]
This error is from different cause. this repo doesn't use `express-status-monitor` package.
