### ISSUE TITLE
How can I implements a callback to use something in the message 

### ISSUE THREAD

**Issue by sostenesapollo12** [vasani-arpit/WBOT#87]
**Is your feature request related to a problem? Please describe.**
No is a problem, it's an improvement.

For example, instead I pass the bot configs to a json file i would pass for a javascript file including a callback function that handles the data and return for me

*example*: 
1 - Someone text me this message :    Show me id 3
2 - the handle function will verify if the message have the pattern : Show me id ${id}
3- The function will catch the id, search in db something and return the data in the handle function
4- Send the message 

sorry for my bad english xd

**Comment by vasani-arpit** [comment]
You can use webhook feature for that. docs and example are provided [here](https://github.com/vasani-arpit/WBOT/blob/master/docs/Webhook-example.md)

You need to create a server using php or expressJS or any other server side language and provide that server endpoint URL to wbot in `bot.json` as a webhook property. WBOT will call that endpoint every time it receives message and reply with the message your server sends. 


Closing. Reopen if required.
