### ISSUE TITLE
Get groups participants

### ISSUE THREAD

**Issue by cidocamp0s** [vasani-arpit/WBOT#91]
I am trying to get all participants from a group. But 
the following issue occurs:
![Sem título](https://user-images.githubusercontent.com/24815351/72691087-5c6ee900-3b01-11ea-80e7-c66262c04e5c.png)

**Comment by vasani-arpit** [comment]
![image](https://user-images.githubusercontent.com/6497827/72701426-4bf85600-3b75-11ea-9b9a-16e2001ee372.png)


The values are there you just need to do a minor modification in WAPI.js.

I think [this](https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/772) will resolve your problem 

Closing. Reopen if needed.

**Comment by cidocamp0s** [comment]
Thanks.
