### ISSUE TITLE
get more user data via webhook

### ISSUE THREAD

**Issue by panteLx** [vasani-arpit/WBOT#95]
**Is your feature request related to a problem? Please describe.**
currently it isnt possible to get the user that wrote a message in a group. you will always get the group creator number instead (smth like 491522773xxxx-1528797493@g.us). 

**Describe the solution you'd like**
Would be good to get the author number instead of the chatId as webhook data field

**Additional context**
getting the author data instead of the chatId makes it a way easier to create a permission system (so only number X can use command !y).

**Comment by oOHiyoriOo** [comment]
hm iam not sure but i think i actually get the correct number using webhook... let me check it out!
meanwhile: 
what webhook you're using ? (lang?)

**Comment by panteLx** [comment]
using php :) pls share ur working example :3

**Comment by oOHiyoriOo** [comment]
Just checked and you're right!
first msg by a friend second one is from me both show my number.

![image](https://user-images.githubusercontent.com/44544317/72930620-9daf0500-3d5c-11ea-9735-0a6e96e7c9a9.png)

**Comment by weblinggau** [comment]
> using php :) pls share ur working example :3

Can you share your code php webhook.. I also have the same problem

**Comment by oOHiyoriOo** [comment]
sry for the late answer.
i have to disappoint u iam using python for my webhook its much more secrure and has the same sunctions as far as i know,
one of many reasons for me to not use php.
