### ISSUE TITLE
Example webhook with php

### ISSUE THREAD

**Issue by weblinggau** [vasani-arpit/WBOT#97]
I use php for webhook but nothing happens, maybe someone can help share php webhook.

**Comment by vasani-arpit** [comment]
Sure. As discussed planning to make a video for that. I don't know much of php but will try that. https://github.com/vasani-arpit/WBOT/issues/81#issuecomment-569608126

**Comment by weblinggau** [comment]
great, I made a webhook example with php, I thought the data received was an object and that the object had to be sent back too. Here's a sample code and it works
`
<?php 
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET,PUT,POST,DELETE,PATCH,OPTIONS');
header('Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization,X-Authorization');
$data = json_decode(file_get_contents('php://input'));
$user = $data->user;
$msg =$data->text;
$type =  $data->type;
if ($msg == 'great') {
	$resp = array(['text' => "message like great i like it",
				  'type' => "message"]);

	$json = json_encode($resp);
	echo ($json);

} elseif ($msg == 'ping') {
	$resp = array(['text' => "example ping chat",
				  'type' => "message"]);

	$json = json_encode($resp);
	echo ($json);
}
?>

**Comment by impozzible** [comment]
https://drive.google.com/file/d/1XREpk7RroD8UwWk-Kdkh-dj72_L8HS68/view?usp=sharing
