### ISSUE TITLE
Media import and storage?

### ISSUE THREAD

**Issue by SentineL771** [vasani-arpit/WBOT#98]
How can we get all media content (video files may not be due to size) from Whatsapp?

### A short example:

Sender: 45654.jpg
_WBOT: Hello. What topic is this file on?_

> A) Nature B) Technology

Sender: A (chose)
_WBOT: Your file has been saved in the nature folder. Thank you_

**Is this possible ?**

**Comment by oOHiyoriOo** [comment]
what language u want it to be ?

**Comment by oOHiyoriOo** [comment]
sadly i cant get images in good quality ...
but here i have it for u:
https://github.com/oOHiyoriOo/Whatsapp-Image-Sorter

**Comment by iskenderalpsakarya** [comment]
> what language u want it to be ?
> e.g. Python, Java, PhP ?

Javascript please :)

**Comment by iskenderalpsakarya** [comment]
> sadly i cant get images in good quality ...
> but here i have it for u:
> https://github.com/oOHiyoriOo/Whatsapp-Image-Sorter

How do I do this with WBOT? Do you have a for use?

**Comment by oOHiyoriOo** [comment]
i can make one i js too just gimma some time.
with this pyhton example u setup the WBOT to use http://127.0.01:1311/
like this:
![image](https://user-images.githubusercontent.com/44544317/73193900-9a849200-412b-11ea-936b-4a44ca86e712.png)

than run both the Main.py + WBOT and it should handle the rest.

**Comment by blubbll** [comment]
> i can make one i js too just gimma some time.
> with this pyhton example u setup the WBOT to use http://127.0.01:1311/
> like this:
> ![image](https://user-images.githubusercontent.com/44544317/73193900-9a849200-412b-11ea-936b-4a44ca86e712.png)
> 
> than run both the Main.py + WBOT and it should handle the rest.

Sry to clip in, but youre just de-base64' img the preview file right?
It currently IS possible to get the file blob and save it (well, i found to do it manually in non-headless mode via gui interactions). This should be possible with a javascript click invoke on the latest channel and then scanning for the latest or more img(?, i dont remember anymore) tags and download their blobs to files with js

**Comment by oOHiyoriOo** [comment]
yup should be possible.
maybe in the inject js ? 
i thought he want a example using the webhook.
